# Inspect Ingested Data Tables

This notebook helps you inspect the SQLite bronze tables used by Skimmer.

- Default DB path: `data/skimmer.db`
- Override with env var: `SKIMMER_DB_PATH`
- It lists tables, shows schema, row counts, and recent records.

In [10]:
import json
import os
import sqlite3
from pathlib import Path

import pandas as pd
from IPython.display import display

DEFAULT_DB_PATH = Path('data/skimmer.db')
DB_PATH = Path(os.environ.get('SKIMMER_DB_PATH', DEFAULT_DB_PATH)).expanduser()

print(f'Using database: {DB_PATH.resolve()}')
if not DB_PATH.exists():
    raise FileNotFoundError(f'Database not found: {DB_PATH}')

Using database: /home/orangepi/code_projects/skimmer/data/skimmer.db

In [11]:
connection = sqlite3.connect(DB_PATH)

tables_df = pd.read_sql_query(
    """
    SELECT name AS table_name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name
    """,
    connection,
)

if tables_df.empty:
    raise RuntimeError('No tables found in the database.')

display(tables_df)

                             table_name
0   bronze_socialblade_channel_profiles
1      bronze_socialblade_channel_stats
2         bronze_vidiq_channel_profiles
3            bronze_vidiq_channel_stats
4                bronze_youtube_skimmed
5       bronze_youtubeapi_channel_stats
6         bronze_youtubeapi_video_stats
7                   collection_attempts
8                     collection_errors
9                         profile_queue
10              youtube_api_quota_usage

In [12]:
def table_schema(table_name: str) -> pd.DataFrame:
    return pd.read_sql_query(f"PRAGMA table_info({table_name})", connection)


def row_count(table_name: str) -> int:
    query = f"SELECT COUNT(*) AS row_count FROM {table_name}"
    return int(pd.read_sql_query(query, connection).iloc[0]['row_count'])


def preview_table(table_name: str, limit: int = 25) -> pd.DataFrame:
    schema = table_schema(table_name)
    column_names = schema['name'].tolist()
    order_column = next(
        (
            column
            for column in ('id', 'last_seen_at', 'observed_at', 'occurred_at', 'created_at', 'latest_video_at')
            if column in column_names
        ),
        next((column for column, is_primary_key in zip(schema['name'], schema['pk']) if is_primary_key), None),
    )
    order_by = f' ORDER BY "{order_column}" DESC' if order_column else ''
    query = f'SELECT * FROM "{table_name}"{order_by} LIMIT {int(limit)}'
    df = pd.read_sql_query(query, connection)

    if 'raw_record_json' in df.columns:
        def parse_raw(value):
            if value is None:
                return None
            try:
                return json.loads(value)
            except (json.JSONDecodeError, TypeError):
                return value

        df['raw_record_json_parsed'] = df['raw_record_json'].map(parse_raw)

    return df

In [13]:
summary_rows = []
for table_name in tables_df['table_name'].tolist():
    summary_rows.append({'table_name': table_name, 'row_count': row_count(table_name)})

summary_df = pd.DataFrame(summary_rows).sort_values(['row_count', 'table_name'], ascending=[False, True])
display(summary_df)

                             table_name  row_count
4                bronze_youtube_skimmed      18890
7                   collection_attempts       5582
6         bronze_youtubeapi_video_stats       5482
9                         profile_queue       2802
3            bronze_vidiq_channel_stats       1828
8                     collection_errors        780
2         bronze_vidiq_channel_profiles        471
1      bronze_socialblade_channel_stats        311
5       bronze_youtubeapi_channel_stats        211
10              youtube_api_quota_usage          1
0   bronze_socialblade_channel_profiles          0

In [14]:
for table_name in tables_df['table_name'].tolist():
    print('\n' + '=' * 100)
    print(f'TABLE: {table_name}')
    print('=' * 100)

    print('\nSchema:')
    display(table_schema(table_name))

    print('\nLatest rows:')
    display(preview_table(table_name, limit=20))

====================================================================================================
TABLE: bronze_socialblade_channel_profiles
====================================================================================================

Schema:

   cid               name     type  notnull dflt_value  pk
0    0                 id  INTEGER        0       None   1
1    1         channel_id     TEXT        1       None   0
2    2       channel_name     TEXT        0       None   0
3    3       channel_type     TEXT        0       None   0
4    4            country     TEXT        0       None   0
5    5         created_at     TEXT        0       None   0
6    6  subscribers_total                 0       None   0
7    7        views_total                 0       None   0
8    8       videos_total                 0       None   0
9    9        data_digest     TEXT        1       None   0

Latest rows:

Empty DataFrame
Columns: [id, channel_id, channel_name, channel_type, country, created_at, subscribers_total, views_total, videos_total, data_digest]
Index: []

====================================================================================================
TABLE: bronze_socialblade_channel_stats
====================================================================================================

Schema:

    cid                name     type  notnull dflt_value  pk
0     0                  id  INTEGER        0       None   1
1     1          channel_id     TEXT        1       None   0
2     2  subscribers_change                 0       None   0
3     3   subscribers_total                 0       None   0
4     4        views_change                 0       None   0
5     5         views_total                 0       None   0
6     6       videos_change                 0       None   0
7     7        videos_total                 0       None   0
8     8        earnings_low                 0       None   0
9     9       earnings_high                 0       None   0
10   10         data_digest     TEXT        1       None   0

Latest rows:

,id,channel_id,subscribers_change,subscribers_total,views_change,views_total,videos_change,videos_total,earnings_low,earnings_high,data_digest
0,311,UCp90hB8_sqLcEEXVgiUCbcw,1000.0,251000,11301,11248718,NaN,377,3,45,430b7ac14efa41886e1a53e8cc17b9192d0d2fb540dabf...
1,310,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,14796,11237417,2.0,377,4,59,6929dab2336ccc2db81c7261cdd7d0b945f585f72db020...
2,309,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,11370,11222621,NaN,375,3,45,6ccebe1db6649eec7fd114d929b677d1befb401d77d645...
3,308,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,19442,11211251,NaN,375,5,78,1f799d2787a707e227bc45ae6fcc7d0ec952acb90fb1f1...
4,307,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,14745,11191809,1.0,375,4,59,93ccf1df46865a2e90d7bce25037bc6729502168ba3c41...
5,306,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,17594,11177064,1.0,374,4,70,252d86095d1d2515403d8274ef141f21f89aa93c242482...
6,305,UCp90hB8_sqLcEEXVgiUCbcw,1000.0,250000,20429,11159470,1.0,373,5,82,77cc635d570cf1c159b75639e1f4e084f4acbc6b7dae8a...
7,304,UCp90hB8_sqLcEEXVgiUCbcw,NaN,249000,23942,11139041,2.0,372,6,96,c2c1c3781f2e1886d8ad886a2c36fe2725edf705cf0515...
8,303,UCp90hB8_sqLcEEXVgiUCbcw,NaN,249000,11693,11115099,1.0,370,3,47,05fb8717032356a699c0571ab8023781ec84007f5c2ed8...
9,302,UCp90hB8_sqLcEEXVgiUCbcw,NaN,249000,14035,11103406,NaN,369,4,56,502d2ab81d38c90a273a9dda8910cb2da7d27e1876bbf9...
10,301,UCp90hB8_sqLcEEXVgiUCbcw,NaN,249000,15839,11089371,NaN,369,4,63,e5c6f8241048f778415a4fd0496a8a0d36db77c213695c...
11,300,UCp90hB8_sqLcEEXVgiUCbcw,1000.0,249000,18458,11073532,1.0,369,5,74,582adb96d83e0c93ba3e9308e67439d913bd53d3ebad65...
12,299,UCp90hB8_sqLcEEXVgiUCbcw,NaN,248000,22187,11055074,1.0,368,6,89,e35a2afaaadd47c030d07effa1f3a529f40160e9563d53...
13,298,UCp90hB8_sqLcEEXVgiUCbcw,NaN,248000,24407,11032887,1.0,367,6,98,e817fc8cd35542fc68b46c8677bd4ff4fea10d4eb5a121...
14,297,UC97zsM9Vvmwz0Tmy7-G_pow,1000.0,150000,270511,10744827,22.0,227,68,1100,e69c92160f38c719379ad79235fd499668a3002efab39b...
15,296,UC97zsM9Vvmwz0Tmy7-G_pow,1000.0,149000,1802570,10474316,100.0,205,0,0,7fc72e1c5007807f360325d24e95d249359c00c1d5eed7...
16,295,UC97zsM9Vvmwz0Tmy7-G_pow,2000.0,148000,58196,12276886,68.0,305,0,0,861ec04dcf581beb00f40c349d8c01acde6635f213e068...
17,294,UC97zsM9Vvmwz0Tmy7-G_pow,1000.0,146000,89359,12335082,2.0,237,22,357,97aa603bb6be0930722adf428ee50e626529bc8ff3d776...
18,293,UC97zsM9Vvmwz0Tmy7-G_pow,NaN,145000,1217090,12245723,45.0,239,0,0,09dd6249d650ca39b69a258914fce52f77568af5291bc7...
19,292,UC97zsM9Vvmwz0Tmy7-G_pow,1000.0,145000,1005680,13462813,10.0,194,251,4000,6e99580f3482f656c5bfff2a28387e7218baaf7fba1e54...

====================================================================================================
TABLE: bronze_vidiq_channel_profiles
====================================================================================================

Schema:

    cid                        name     type  notnull dflt_value  pk
0     0                          id  INTEGER        0       None   1
1     1                  channel_id     TEXT        1       None   0
2     2                channel_name     TEXT        0       None   0
3     3                   joined_at     TEXT        0       None   0
4     4                    location     TEXT        0       None   0
5     5                    category     TEXT        0       None   0
6     6                videos_total                 0       None   0
7     7           subscribers_total                 0       None   0
8     8                 views_total                 0       None   0
9     9  estimated_monthly_earnings                 0       None   0
10   10              content_period     TEXT        0       None   0
11   11           long_form_uploads                 0       None   0
12   12              shorts_uploads                 0       None   0
13   13             long_form_views                 0       None   0
14   14                shorts_views                 0       None   0
15   15      ranking_30_day_country     TEXT        0       None   0
16   16    ranking_30_day_worldwide     TEXT        0       None   0
17   17                 data_digest     TEXT        1       None   0

Latest rows:

,id,channel_id,channel_name,joined_at,location,category,videos_total,subscribers_total,views_total,estimated_monthly_earnings,content_period,long_form_uploads,shorts_uploads,long_form_views,shorts_views,ranking_30_day_country,ranking_30_day_worldwide,data_digest
0,471,@DisguisedToast,Disguised Toast,"Apr 07, 2015",United States,Gaming,About,3770000,1610000000,28000,"Since Jan 01, 2026",None,None,None,None,US,"#2,987",3207c49a162c11f3431b4ae61dd0dd1660cbb6de2d142d...
1,470,@brewstew,brewstewfilms,"Feb 16, 2013",United States,Entertainment,About,3670000,1350000000,20000,"Since Jan 01, 2026",None,None,None,None,US,"#3,088",34694e420ec27d9af56162e8c83f8a413bc7ac8e669df1...
2,469,@Blesiv,Blesiv,"May 10, 2015",United States,Food,About,1760000,160490000,12000,"Since Jan 01, 2026",None,None,None,None,US,"#7,700",f3f70116333e51d2a08e6ade218042b8e7bce929ada444...
3,468,@RosieandCharlize,Rosie and Charlize,"Feb 23, 2026",Unknown,Music,About,6250,693640,164,"Since Feb 24, 2026",None,None,None,None,Worldwide,"#5,005,505",5468e34c3c0cb9d2c4ab397a46f4bd43ba9b3b55a04baf...
4,467,@AustinPBS,Austin PBS,"May 23, 2007",United States,Entertainment,About,30400,11030000,270,"Since Jan 01, 2026",None,None,None,None,US,"#236,425",1cd13658c43dbf643dc9bc2a5c0eaf1c7948f7dabb2dec...
5,466,@Nerdforge,Nerdforge,"Nov 12, 2015",Norway,Lifestyle,About,3990000,461920000,4000,"Since Jan 01, 2026",None,None,None,None,🇳🇴,NO,e4d36b694074d71d54328793bc24c7d738d5835506e8c1...
6,465,@TheoVon,Theo Von,"Mar 03, 2006",United States,Entertainment,About,4670000,1130000000,10000,"Since Jan 01, 2026",None,None,None,None,US,"#2,251",c08dfdc4e43bfe7ca9bb02ad8cfa01c531064f637b858b...
7,464,@kwtxnews10,KWTX News10,"Nov 22, 2010",United States,News-&-Politics,About,26800,14350000,1000,"Since Jan 01, 2026",None,None,None,None,US,"#255,323",db236b73099d99908ef5b98594768c855a917da9f3b7bf...
8,463,@RachPlusFive,Rach Plus Five,"Mar 11, 2020",United States,Lifestyle,About,71900,10860000,65,"Since Jan 01, 2026",None,None,None,None,US,"#135,078",e21840f6f6091f1fd1ce37571885b78fa3193a06f5ff91...
9,462,@Huskybythegeek,Husky by the Geek,"Jan 05, 2012",France,Gaming,About,106000,43620000,761,"Since Jan 01, 2026",None,None,None,None,FR,"#8,119",4201cba8926b6c40a93eea743156baf8ea0a50d34a72ff...
10,461,@Vivilly,Vivilly,"Mar 15, 2021",United States,Gaming,About,1800000,1730000000,30000,"Since Jan 01, 2026",None,None,None,None,US,"#7,464",68eb8f749c0546e4558b8cdb487d6207029133338ea8e1...
11,460,@TheAspieWorld,The Aspie World,"Jul 11, 2013",United Kingdom,Health,About,299000,31980000,1000,"Since Jan 01, 2026",None,None,None,None,GB,"#5,272",f26df2cb21a857ceb2f327b865a59249141add0ca9df93...
12,459,@DotoDoya,DotoDoya,"Jul 14, 2017",Unknown,Gaming,About,1030000,548330000,13000,"Since Jan 01, 2026",None,None,None,None,Worldwide,"#70,598",b2165a88875dbf0d2a74c2f29c6495e4c0e0541a0df445...
13,458,@Bobdoessports,Bob Does Sports,"Sep 30, 2021",Unknown,Sports,About,1480000,420690000,29000,"Since Jan 01, 2026",None,None,None,None,Worldwide,"#45,910",69ce4abe3a9e1ae879f892ad38e3a00eb387c8e658b469...
14,457,@CBSPittsburgh,CBS Pittsburgh,"Jul 21, 2014",Unknown,Lifestyle,About,204000,222810000,5000,"Since Jan 01, 2026",None,None,None,None,Worldwide,"#358,644",54dabd5a7ad41856d54701688730f3692330ea41c08a5c...
15,456,@Tarayummy,Tarayummy,"Jan 02, 2012",United States,Lifestyle,About,2410000,210640000,19000,"Since Jan 01, 2026",None,None,None,None,US,"#5,315",8f6c575ab2a3c982a0154c98ed30c6b6ffa7183bfec251...
16,455,@ChillingScares,Chilling Scares,"Nov 28, 2020",United States,Entertainment,About,2800000,584390000,29000,"Since Jan 01, 2026",None,None,None,None,US,"#4,392",097760737439abcee3dde68746df621c516f2302fc72d8...
17,454,@laabsifeeyeofficial,NUUR OFFICIAL,"Jul 22, 2018",Kenya,Lifestyle,About,56500,8600000,6,"Since Jan 01, 2026",None,None,None,None,🇰🇪,KE,c14012c2030557259285dae4c429ddd7e795d7d23d59c8...
18,453,@westmontrich,Westmont Rich,"Dec 12, 2019",United States,Lifestyle,About,11600,828860,393,"Since Jan 01, 2026",None,None,None,None,US,"#413,830",4ea60b921985f258a878a2c12a5568da9f0c9ff5dee9cd...
19,452,@daddywellness,Daddy Wellness,"Aug 26, 2020",United States,Entertainment,About,128000,19340000,1000,"Since Jan 01, 2026",None,None,None,None,US,"#88,435",825d9972faa237214f1492006e5d7ee83df6f22fb944cf...

====================================================================================================
TABLE: bronze_vidiq_channel_stats
====================================================================================================

Schema:

    cid                name     type  notnull dflt_value  pk
0     0                  id  INTEGER        0       None   1
1     1          channel_id     TEXT        1       None   0
2     2        channel_name     TEXT        0       None   0
3     3         subscribers                 0       None   0
4     4  subscribers_change                 0       None   0
5     5               views                 0       None   0
6     6        views_change                 0       None   0
7     7        earnings_low                 0       None   0
8     8       earnings_high                 0       None   0
9     9          engagement                 0       None   0
10   10    upload_frequency                 0       None   0
11   11      average_length                 0       None   0
12   12         data_digest     TEXT        1       None   0

Latest rows:

,id,channel_id,channel_name,subscribers,subscribers_change,views,views_change,earnings_low,earnings_high,engagement,upload_frequency,average_length,data_digest
0,1828,@brewstew,brewstewfilms,3670000,None,1350000000,None,20000,None,None,None,None,5bca64a6b9d618887da4f403e9d62d9f076c8c229783af...
1,1827,@Blesiv,Blesiv,1760000,None,160490000,None,12000,None,None,None,None,a971cc585db77360b7888c58b8bd9443d683ced1cbf001...
2,1826,@RosieandCharlize,Rosie and Charlize,6250,None,693640,None,164,None,None,None,None,895ed39371ef4fe6f37721cd9db66dcbc5aa7ef76b177a...
3,1825,@AustinPBS,Austin PBS,30400,None,11030000,None,270,None,None,None,None,551ea71588ce9b9fc0cf8306845c82781fe822b8156551...
4,1824,@kwtxnews10,KWTX News10,26800,None,14350000,None,1000,None,None,None,None,86dd1693edca56178e4375c1f9e87ab41dd2a84ef677c5...
5,1823,@RachPlusFive,Rach Plus Five,71900,None,10860000,None,65,None,None,None,None,ae83ecaf5893251da0073d4537b6e51ac355f6e961978e...
6,1822,@DotoDoya,DotoDoya,1030000,None,548330000,None,13000,None,None,None,None,f6df2c9e60a1183390eaaa6cd0695e1a0bb4d869ffd3ab...
7,1821,@Tarayummy,Tarayummy,2410000,None,210640000,None,19000,None,None,None,None,192857c2847e7090ccbf1fafec3fb58cc8da68e6bae4d7...
8,1820,@ChillingScares,Chilling Scares,2800000,None,584390000,None,29000,None,None,None,None,69bb14d5b103dd72426b322ae256e4246a598514133ff0...
9,1819,@westmontrich,Westmont Rich,11600,None,828860,None,393,None,None,None,None,2d645b37875a30ae70540177620c536e9d8cbd8defbbd4...
10,1818,@daddywellness,Daddy Wellness,128000,None,19340000,None,1000,None,None,None,None,aad895e89a54486e8eceee0e2e1e3db2e04d4bbaed8c7b...
11,1817,@ImPeterMc,PeterMc,272000,None,74390000,None,2000,None,None,None,None,675506e6f4a5f9c7acc70f8246be2f18a8bf46cc18f7c5...
12,1816,@howridiculous,How Ridiculous,24000000,None,15930000000,None,48000,None,None,None,None,5d88c7e0616a0658a3263b68fdb2c48c8747f7610976bd...
13,1815,@legacycom,Legacy.com,277000,None,125110000,None,8000,None,None,None,None,9de26c85b022196d470421cee8995c6ee700d15489fc89...
14,1814,@Poofesure,Poofesure,2700000,None,984530000,None,27000,None,None,None,None,253f722ae27aec9b1dd22d397d14887a06b883e2f10eaf...
15,1813,@ImKevinn,ImKevinn,615000,None,81280000,None,4000,None,None,None,None,44fa6aec6f6b48446f2e7fd0eb9c52c1f1262e0d9ed297...
16,1812,@TheHealthyAmericanPeggyHall,The Healthy American Peggy Hall,189000,None,2120000,None,—,None,None,None,None,4a360662e6dfe045c7170e8f173b1d51549ae37590a6ae...
17,1811,@FirstThingsFirst,First Things First,1100000,None,1090000000,None,40000,None,None,None,None,6e306d7b45b126f1b08130d49954f351eb49ea12393f40...
18,1810,@FDSignifire,F.D Signifier,1210000,None,86740000,None,2000,None,None,None,None,698e91a9f2c544b41ba9fde2dd520e4cd9c7ab9d1a87b9...
19,1809,@DoItOnaDime,Do It On A Dime,2460000,None,461750000,None,5000,None,None,None,None,82c9a24e4fbf5fb4f7e569e3ff253456eb0f204b1cdb69...

====================================================================================================
TABLE: bronze_youtube_skimmed
====================================================================================================

Schema:

    cid                  name     type  notnull dflt_value  pk
0     0                    id  INTEGER        0       None   1
1     1           observed_at     TEXT        1       None   0
2     2    video_published_at     TEXT        1       None   0
3     3           source_file     TEXT        1       None   0
4     4            video_name     TEXT        0       None   0
5     5  channel_display_name     TEXT        0       None   0
6     6                 views     TEXT        0       None   0
7     7                   age     TEXT        0       None   0
8     8            channel_id     TEXT        1       None   0
9     9         record_digest     TEXT        1       None   0
10   10    youtube_channel_id     TEXT        0       None   0

Latest rows:

,id,observed_at,video_published_at,source_file,video_name,channel_display_name,views,age,channel_id,record_digest,youtube_channel_id
0,18890,2026-07-23T03:10:39+00:00,2026-07-22T19:10:39+00:00,https://www.youtube.com,The Scariest Horror Movie I've Ever Watched,DerekFDB,161K views,8 hours ago,@DerekFDB,3c88dda655a1e2de66365168f9b110e64c95f0c0092565...,None
1,18889,2026-07-23T03:10:39+00:00,2026-07-18T03:10:39+00:00,https://www.youtube.com,"I Tried Eating & Drinking Alone in Dublin, Ire...",Gareth Leonard,888K views,5 days ago,@GarethLeonard,29ac9e12ec8e2cb1480c996d80a77e298b48922e13364f...,None
2,18888,2026-07-23T03:10:39+00:00,2026-07-21T03:10:39+00:00,https://www.youtube.com,BEST Reactions to JuicyJacob! (Streamer Univer...,JuicyJacobFan,368K views,2 days ago,@Juicyjacobfan,d35e0052e33a9ec495d35fca4133d5a63c8ef804fe10a4...,None
3,18887,2026-07-23T03:10:39+00:00,2026-07-22T03:10:39+00:00,https://www.youtube.com,"The Weird, Deceitful World of YouTube ""Gurus"" ...",JJJacksfilms,193K views,1 day ago,@jjjacksfilms,ac6dc32f4611833dd7a9bb66aa20b8dbd460364d4ad9ea...,None
4,18886,2026-07-23T03:10:39+00:00,2026-07-22T23:10:39+00:00,https://www.youtube.com,HARRY'S DESPERATE LATE NIGHT CALL BLOWS THIS ...,NEIL SEAN'S DAILY NEWS HEADLINES,32K views,4 hours ago,@NEILSEANSSHOWBIZ,2a0cd6d2efd3749ec09f12651b1275998c680b8f01bf62...,None
5,18885,2026-07-23T03:10:39+00:00,2026-07-22T20:10:39+00:00,https://www.youtube.com,I Bought EVERY Abandoned Product I Could Find,FaZe Rug,595K views,7 hours ago,@rug,b68af57ef3fd9768ffbcd81a22ad670a76a101b4aa54f9...,None
6,18884,2026-07-23T03:10:39+00:00,2026-07-22T20:10:39+00:00,https://www.youtube.com,The new balcony is fitted.,Escape to rural France,168K views,7 hours ago,@escapetoruralfrance,3534c301209eeb368ef873db51e938e3bfb1a598e91a54...,None
7,18883,2026-07-23T03:10:39+00:00,2026-07-22T22:10:39+00:00,https://www.youtube.com,Someone Leaked My Private Videos,imactuallyLazy,225K views,5 hours ago,@imactuallylazy,80a14759970b687c4e708b4495f5b504c4446b64682948...,None
8,18882,2026-07-23T03:10:39+00:00,2026-07-23T02:10:39+00:00,https://www.youtube.com,SML Movie: The World Cup!,SML,279K views,1 hour ago,@SMLMovies,601f02dd5a1b0ad65666997cd3151a2c84619afe8198f8...,None
9,18881,2026-07-23T03:10:39+00:00,2026-06-25T03:10:39+00:00,https://www.youtube.com,Every Angle Grinder Disc Explained In 11 Minutes,Workshop Decoded,142K views,4 weeks ago,@WorkShopDecoded,c9f034be593c43cf86e15673a4552dc4abcdb315301198...,None
10,18880,2026-07-23T03:10:39+00:00,2026-07-22T03:10:39+00:00,https://www.youtube.com,"Here it is, the PERFECTED Solar Titan Build I’...",Llama,57K views,1 day ago,@LlamaD2,db527bc031e3c3e88228802c0a8ce634dc4b2edcf018d7...,None
11,18879,2026-07-23T03:10:39+00:00,2026-07-22T03:10:39+00:00,https://www.youtube.com,Georgia’s Wildest Sheriffs: A Clayton County R...,Tommy G,945K views,1 day ago,@TommyGMcGee,be956cf844af8ced5a95f624f56ff3fa41d799596b6b47...,None
12,18878,2026-07-23T03:10:39+00:00,2026-07-22T03:10:39+00:00,https://www.youtube.com,"The ""Ride The Ducks"" Disaster | Fascinating Ho...",Fascinating Horror,312K views,1 day ago,@FascinatingHorror,28f95c9f1f671334831629af2ad3b3af5a5dfd54473984...,None
13,18877,2026-07-23T03:10:39+00:00,2026-07-23T02:10:39+00:00,https://www.youtube.com,ABC World News Tonight with David Muir Full Br...,ABC News,87K views,1 hour ago,@ABCNews,66a1b22ee047ad23d08a2466b1f9f37814d382b8c42fd6...,None
14,18876,2026-07-23T03:10:39+00:00,2026-07-19T03:10:39+00:00,https://www.youtube.com,Microsoft just dropped a nuke..,Asmongold Clips,916K views,4 days ago,@AsmongoldClips,e8d32f9a4a99e66d86ffb52dad8148334ea35773b76a56...,None
15,18875,2026-07-23T03:10:39+00:00,2026-07-22T03:10:39+00:00,https://www.youtube.com,TikToker Panicking After Caught Faking Charity...,Atozy,520K views,1 day ago,@atozy,0e75ce045d231789f01ba4daeb1aa1f30469e31acd1ee3...,None
16,18874,2026-07-23T03:10:39+00:00,2026-07-23T02:10:39+00:00,https://www.youtube.com,Robert Lewandowski’s DEBUT 🍿 Inter Miami vs. C...,ESPN FC,22K views,1 hour ago,@ESPNFC,8d0ca4a02ecafe733d0035a18f45fae72f79c9153283c1...,None
17,18873,2026-07-23T03:10:39+00:00,2026-07-22T03:10:39+00:00,https://www.youtube.com,Benjamin Netanyahu is a war criminal.,NYC Mayor's Office,2.1M views,1 day ago,@NYCMayorsOffice,bdf05183db2089bd384a839aacb43a0a2d4ba2631ed133...,None
18,18872,2026-07-23T03:10:39+00:00,2026-07-22T19:10:39+00:00,https://www.youtube.com,Valve Accidentally Made the Best Desktop PC I’...,Linus Tech Tips,764K views,8 hours ago,@LinusTechTips,3d6477f7cd9e800405e6c2c727dc494bb19364711a2d9f...,None
19,18871,2026-07-23T03:10:39+00:00,2026-07-19T03:10:39+00:00,https://www.youtube.com,ప్రశ్న రావణ్ కు ఊహించని షాక్ 😱 Social Activist...,The Leo News,949 views,4 days ago,@TheLeoNews,f304868e64d45bc4ac68ac22fb3e4d3a4468970338a357...,None

====================================================================================================
TABLE: bronze_youtubeapi_channel_stats
====================================================================================================

Schema:

    cid                  name     type  notnull dflt_value  pk
0     0                    id  INTEGER        0       None   1
1     1          collected_at     TEXT        1       None   0
2     2            channel_id     TEXT        1       None   0
3     3          channel_name     TEXT        0       None   0
4     4           subscribers                 0       None   0
5     5    subscribers_change                 0       None   0
6     6                 views                 0       None   0
7     7          views_change                 0       None   0
8     8           video_count                 0       None   0
9     9               country     TEXT        0       None   0
10   10  channel_published_at     TEXT        0       None   0
11   11   uploads_playlist_id     TEXT        0       None   0
12   12           data_digest     TEXT        1       None   0

Latest rows:

,id,collected_at,channel_id,channel_name,subscribers,subscribers_change,views,views_change,video_count,country,channel_published_at,uploads_playlist_id,data_digest
0,211,2026-07-23T03:10:56+00:00,UC08LRHNzGMuCcjNr9VqmHWA,VHS-Goldie,604000,None,372243965,None,2330,AT,2011-12-11T18:08:35Z,UU08LRHNzGMuCcjNr9VqmHWA,334fc632e14f715c7f9652b352c500c0e15bb4c2a6f865...
1,210,2026-07-23T03:10:56+00:00,UCSDNfhsWyNOz8foxx5p8unQ,Sweet Project Cars,525000,None,123084114,None,828,US,2013-05-09T11:13:17Z,UUSDNfhsWyNOz8foxx5p8unQ,d8578552efc7f76604b3ae4226bbb232f68e20663ab4f6...
2,209,2026-07-23T03:10:56+00:00,UCouXJsJ-pZycHkaxY9BZtGw,Workshop Decoded,2230,None,139717,None,4,None,2017-02-12T08:52:29Z,UUouXJsJ-pZycHkaxY9BZtGw,cb6e0a6740669b18255a46e546703663536eda93926ca1...
3,208,2026-07-23T03:10:56+00:00,UC8Tm7Xuz8QekHzjsDxgFNnw,WISN 12 News,255000,None,279997140,None,75214,US,2006-10-20T01:48:12Z,UU8Tm7Xuz8QekHzjsDxgFNnw,c2ab0d980c00dbc201c504196d618c258cd18d3b9ad094...
4,207,2026-07-23T03:10:56+00:00,UCjOl2AUblVmg2rA_cRgZkFg,Top Gear,9520000,None,4209697001,None,1870,GB,2006-03-27T10:22:50Z,UUjOl2AUblVmg2rA_cRgZkFg,7fa45223a52157b977f1bbc53aff76510f53fc0c64f509...
5,206,2026-07-23T03:10:56+00:00,UCRneyp6dMqNhIxyPD9Iovrw,Trucker Tim,357000,None,114015599,None,507,GB,2021-05-11T15:24:36.406065Z,UURneyp6dMqNhIxyPD9Iovrw,6bc326aaa4f5a2364f99801cccde0dd35b25e132950f54...
6,205,2026-07-23T03:10:56+00:00,UCz94DIR9Ma9IrRwcOoQJYeA,The Wave24,268000,None,82801105,None,1728,BD,2025-09-30T15:04:34.017972Z,UUz94DIR9Ma9IrRwcOoQJYeA,69ae0c9c362b76c56e959f34b8d8d70a801ce083962862...
7,204,2026-07-23T03:10:56+00:00,UCNEZ7cqaZzYLeyWfTkelkEA,TAOFLEDERMAUS,1650000,None,816017352,None,1329,US,2006-07-23T08:04:48Z,UUNEZ7cqaZzYLeyWfTkelkEA,ef789c16747d34fbaece8fa1b05029ccfe52b9db33ed28...
8,203,2026-07-23T03:10:56+00:00,UCzTu5l2o64P3VN3UcIy7gcg,Stiff Socks Podcast,809000,None,716645096,None,2207,None,2019-01-15T08:20:53Z,UUzTu5l2o64P3VN3UcIy7gcg,923407e3e772a848e12dcd6486b0ef7534ead8993f5af1...
9,202,2026-07-23T03:10:56+00:00,UCZqWWMNLG1gLmhnXLO6qnmQ,Ryan Tempest,1310,None,591355,None,79,US,2025-03-02T11:59:55.480763Z,UUZqWWMNLG1gLmhnXLO6qnmQ,4696f4c9cd0358274bafee176a064ceac831ab31995ecc...
10,201,2026-07-23T03:10:56+00:00,UCh9IfI45mmk59eDvSWtuuhQ,Ryan George,1840000,None,718070112,None,433,CA,2008-12-11T23:37:02Z,UUh9IfI45mmk59eDvSWtuuhQ,4e956a4c5526132b08a92a3bf1f0e8c489ca34e46444c6...
11,200,2026-07-23T03:10:56+00:00,UCS5297aXIngj9gDHAdTerQw,Nick AR,465000,None,84340662,None,352,US,2021-11-28T19:44:02.230327Z,UUS5297aXIngj9gDHAdTerQw,d82a2a2b20ba9da9edb8b671f1dda69e8d7e079729e1ec...
12,199,2026-07-23T03:10:56+00:00,UChUAaNhjdc1aN5f_29BPrhw,MythBusters,728000,None,136753310,None,1224,GB,2023-08-17T14:50:08.235859Z,UUhUAaNhjdc1aN5f_29BPrhw,177408ce8c012fd8198f8531ac88893c83d7f5c5f70947...
13,198,2026-07-23T03:10:56+00:00,UCGfpIu9mtMMRQ15NDIkRyFA,Betting On Alaska,125000,None,8950600,None,82,None,2023-05-19T10:22:36.454325Z,UUGfpIu9mtMMRQ15NDIkRyFA,abd180bcea2df3c10a0b64c771f04195a4f09e25d64ada...
14,197,2026-07-23T03:10:56+00:00,UCSF0lr-54mpTiCjWli1Ty1A,Max Maker,160000,None,16062304,None,127,GB,2011-05-03T21:29:01Z,UUSF0lr-54mpTiCjWli1Ty1A,2e0dfc904af993faa1bc503a18f96f10ac7ec8267b18c9...
15,196,2026-07-23T03:10:56+00:00,UCPdaxSov0mgwh77JvjQO2jQ,Man Carrying Thing,929000,None,356048290,None,894,None,2011-07-14T01:01:10Z,UUPdaxSov0mgwh77JvjQO2jQ,a2191d8d4628c0d8e9d7212f74d240ce64e2e8704f7299...
16,195,2026-07-23T03:10:56+00:00,UCLLpxcworT8275nBXODXyqw,M539 Restorations,769000,None,145879632,None,195,DE,2014-03-13T16:57:42Z,UULLpxcworT8275nBXODXyqw,c5a874e877aadda82234b942ea7762186196a79ebf7b7a...
17,194,2026-07-23T03:10:56+00:00,UCFcyPLVTb_5r3JYMdzHoZaw,Llama,114000,None,40978532,None,888,US,2021-06-16T17:21:43.473608Z,UUFcyPLVTb_5r3JYMdzHoZaw,f7804f7b94bf22093e25b0232d9d561f697ae36e82bbf4...
18,193,2026-07-23T03:10:56+00:00,UCMUyG01MXNeiTykIlvWwIRQ,JJJacksfilms,770000,None,97027566,None,174,US,2022-10-25T19:26:31.65751Z,UUMUyG01MXNeiTykIlvWwIRQ,e73a03474687c54ee6913e589091ebb6cba35bf9e9e5b6...
19,192,2026-07-23T03:10:56+00:00,UCkWQ0gDrqOCarmUKmppD7GQ,JayzTwoCents,4330000,None,1294860886,None,2719,US,2012-08-26T20:24:44Z,UUkWQ0gDrqOCarmUKmppD7GQ,2c8ced362f9084dfcdecdb500ef4f5d3cdf7fb12d21979...

====================================================================================================
TABLE: bronze_youtubeapi_video_stats
====================================================================================================

Schema:

    cid              name     type  notnull dflt_value  pk
0     0                id  INTEGER        0       None   1
1     1      collected_at     TEXT        1       None   0
2     2          video_id     TEXT        1       None   0
3     3        channel_id     TEXT        1       None   0
4     4             title     TEXT        0       None   0
5     5      published_at     TEXT        0       None   0
6     6  duration_seconds                 0       None   0
7     7       category_id     TEXT        0       None   0
8     8             views                 0       None   0
9     9             likes                 0       None   0
10   10          comments                 0       None   0
11   11       data_digest     TEXT        1       None   0

Latest rows:

,id,collected_at,video_id,channel_id,title,published_at,duration_seconds,category_id,views,likes,comments,data_digest
0,5482,2026-07-23T03:11:36+00:00,8-XCFd6utF8,UC08LRHNzGMuCcjNr9VqmHWA,Nella Martinetti - Sing noch einmal die Tarant...,2026-07-14T17:47:40Z,151,10,15859,141,15,fb864537483200a63e384127ac53a19ae199f80bd53ab7...
1,5481,2026-07-23T03:11:36+00:00,Dvpus6pfY5o,UC08LRHNzGMuCcjNr9VqmHWA,Die Wildecker Herzbuben - In meiner kleinen Kn...,2026-07-14T17:47:52Z,117,10,3872,49,1,bfe48cb14cc745f75c30c075d41332935d354049de504a...
2,5480,2026-07-23T03:11:36+00:00,1VO_yyCigUc,UC08LRHNzGMuCcjNr9VqmHWA,Original Tiroler Echo - Nimm dir Zeit für d' M...,2026-07-14T17:48:02Z,183,10,1229,82,4,8c41ca7c9755e504b3c4453d60e377b1f998a0e509f7c2...
3,5479,2026-07-23T03:11:36+00:00,ys1d-fECtWc,UC08LRHNzGMuCcjNr9VqmHWA,"Bachler Buam - Veronika, i bleib' heit Nacht b...",2026-07-15T11:07:18Z,168,10,2213,39,2,a02748e5019dec44108fb48287b588e07c2c8cd8da946d...
4,5478,2026-07-23T03:11:36+00:00,waOCCTfzB5M,UC08LRHNzGMuCcjNr9VqmHWA,Die 4 Holterbuam - Schau nur her - 1998,2026-07-15T14:00:19Z,176,10,3978,28,1,9f50c516e831fb9d342578460cb7ed5b6323b5606d763f...
5,5477,2026-07-23T03:11:36+00:00,MfBccSNlnkE,UC08LRHNzGMuCcjNr9VqmHWA,Edlseer Trio - Mir san drei echte Steirer - 1995,2026-07-15T17:21:46Z,149,10,5298,82,5,056b237a0540abca12154c9811557764c206e92c594be7...
6,5476,2026-07-23T03:11:36+00:00,GCaI9qxniKQ,UC08LRHNzGMuCcjNr9VqmHWA,Edlseer Trio - Uafoch stoark (Einfach stark) -...,2026-07-16T15:42:45Z,166,10,3501,71,5,0cb8a73e5ce4efb069ff6621170f5d1c1e33f3e9952840...
7,5475,2026-07-23T03:11:36+00:00,1UcEpKSgTF4,UC08LRHNzGMuCcjNr9VqmHWA,Slavko Avsenik & die jungen Oberkrainer - Hit-...,2026-07-16T15:44:13Z,265,10,2233,112,6,df008d77d3d9f5fd8a21e0d2697abc2c7a41ffa99d871f...
8,5474,2026-07-23T03:11:36+00:00,UnV-R2g6cps,UC08LRHNzGMuCcjNr9VqmHWA,Das Hellberg-Duo - Himmelblaues Wochenende - 1979,2026-07-16T15:45:41Z,159,10,3365,56,5,a1e8bba4ccd1394f97ad9988124b5030b3db011989c8cf...
9,5473,2026-07-23T03:11:36+00:00,itm5YMw0iUE,UC08LRHNzGMuCcjNr9VqmHWA,Eberhard Hertel - Wenn das kein Grund zum Feie...,2026-07-21T14:14:27Z,196,10,404,27,0,5984402221a1fc56538e65e7b53269699de44ec5abc757...
10,5472,2026-07-23T03:11:36+00:00,U-X8J7MonDA,UC08LRHNzGMuCcjNr9VqmHWA,Hans & Ellen Kollmannsberger - Medley - 1979,2026-07-21T14:14:32Z,161,10,686,26,0,0f1ed7e0e4302f44f22ba384746aba3fc12b7b0447d488...
11,5471,2026-07-23T03:11:36+00:00,iFYKYbiRO9M,UC08LRHNzGMuCcjNr9VqmHWA,AlpenRebellen - A bisserl Woodstock - 2000,2026-07-21T14:15:16Z,191,10,504,30,1,925a4dd8adc811e8a99626818417605571cda3584cb847...
12,5470,2026-07-23T03:11:35+00:00,mIeSeTMKfGI,UCSDNfhsWyNOz8foxx5p8unQ,How To DYE Your Car or Truck Cloth Seats or Ca...,2026-06-25T21:00:05Z,140,2,1903,123,12,69f564db596e32f652a22d0aedc385ce7cacc025f4e37b...
13,5469,2026-07-23T03:11:35+00:00,OayJZtW0Vts,UCSDNfhsWyNOz8foxx5p8unQ,How To Clean & Sanitize Your A/C System in You...,2026-06-26T22:00:36Z,650,2,3790,223,16,06f423e0aba6b57903e1b6172a5eb1d8811b07a2ad62a8...
14,5468,2026-07-23T03:11:35+00:00,9M_ivW2t6vI,UCSDNfhsWyNOz8foxx5p8unQ,Let's FIX Your Dirty NON-WORKING KEY FOB! EAS...,2026-06-28T21:00:06Z,214,2,2317,148,14,52787a7fd05b7e6fa57c22785146541e0f1ea4999bccbf...
15,5467,2026-07-23T03:11:35+00:00,iXZDyZpgUtI,UCSDNfhsWyNOz8foxx5p8unQ,Will Tire Shine Engine Cleaning RUIN Your Alte...,2026-07-04T11:28:03Z,98,2,1982,166,25,f6de5a309b6d57d7290c9b35ea42cdb54bac329b9468a3...
16,5466,2026-07-23T03:11:35+00:00,55fpwoA2Baw,UCSDNfhsWyNOz8foxx5p8unQ,How To Remove a Seized and Rusted Pitman Arm/S...,2026-07-09T17:00:20Z,166,2,1098,103,20,93bbfbfcbd8664743ff877a7c826577abb9262c57f3659...
17,5465,2026-07-23T03:11:35+00:00,JySG-AnhF14,UCSDNfhsWyNOz8foxx5p8unQ,How To REMOVE Old JUNK GREASE & Inject PURE Sy...,2026-07-11T00:00:21Z,174,2,1759,116,10,88c75df12c9b50b1a87a780bb6e6ff19a595ea1ef7ec9a...
18,5464,2026-07-23T03:11:35+00:00,JBs6RXHYXFI,UCSDNfhsWyNOz8foxx5p8unQ,Is Your PULLEY SQUEAKING or Is it Your Drive B...,2026-07-16T20:26:05Z,158,2,1451,120,12,ad6f71f0f6f652870877d884afbd3579a45004c50661a7...
19,5463,2026-07-23T03:11:35+00:00,7wZAl5H38jA,UCSDNfhsWyNOz8foxx5p8unQ,How To Fix a Hole in ALL Cloth Seating...Car o...,2026-07-19T18:00:33Z,312,2,2955,216,14,2f5ea836a8c4a7db2a8d2bd8ec9bba3a95a9cf52015906...

====================================================================================================
TABLE: collection_attempts
====================================================================================================

Schema:

   cid             name     type  notnull dflt_value  pk
0    0               id  INTEGER        0       None   1
1    1      occurred_at     TEXT        1       None   0
2    2           source     TEXT        1       None   0
3    3      channel_key     TEXT        1       None   0
4    4       identifier     TEXT        1       None   0
5    5  identifier_kind     TEXT        1       None   0
6    6       source_url     TEXT        1       None   0
7    7          outcome     TEXT        1       None   0
8    8     failure_type     TEXT        0       None   0

Latest rows:

,id,occurred_at,source,channel_key,identifier,identifier_kind,source_url,outcome,failure_type
0,5582,2026-07-23T02:38:23+00:00,vidiq,@nicholaslighttv,@NicholasLightTV,handle,https://vidiq.com/youtube-stats/channel/@Nicho...,failed,metrics_unavailable
1,5581,2026-07-23T02:38:07+00:00,vidiq,@jeffostroff,@jeffostroff,handle,https://vidiq.com/youtube-stats/channel/@jeffo...,failed,metrics_unavailable
2,5580,2026-07-23T02:37:51+00:00,vidiq,@disguisedtoast,@DisguisedToast,handle,https://vidiq.com/youtube-stats/channel/@Disgu...,succeeded,None
3,5579,2026-07-23T02:37:33+00:00,vidiq,@chanceshomeworld,@chanceshomeworld,handle,https://vidiq.com/youtube-stats/channel/@chanc...,failed,metrics_unavailable
4,5578,2026-07-23T02:37:17+00:00,vidiq,@brewstew,@brewstew,handle,https://vidiq.com/youtube-stats/channel/@brewstew,succeeded,None
5,5577,2026-07-23T02:36:59+00:00,vidiq,@blesiv,@Blesiv,handle,https://vidiq.com/youtube-stats/channel/@Blesiv,succeeded,None
6,5576,2026-07-23T02:36:42+00:00,vidiq,@deenthegreat1,@deenthegreat1,handle,https://vidiq.com/youtube-stats/channel/@deent...,failed,metrics_unavailable
7,5575,2026-07-23T02:36:25+00:00,vidiq,@rosieandcharlize,@RosieandCharlize,handle,https://vidiq.com/youtube-stats/channel/@Rosie...,succeeded,None
8,5574,2026-07-23T02:36:06+00:00,vidiq,@statn1me,@statn1me,handle,https://vidiq.com/youtube-stats/channel/@statn1me,failed,metrics_unavailable
9,5573,2026-07-23T02:35:50+00:00,vidiq,@scotsanimereaction,@ScotsAnimeReaction,handle,https://vidiq.com/youtube-stats/channel/@Scots...,failed,metrics_unavailable
10,5572,2026-07-23T02:35:34+00:00,vidiq,@austinpbs,@AustinPBS,handle,https://vidiq.com/youtube-stats/channel/@Austi...,succeeded,None
11,5571,2026-07-23T02:35:15+00:00,vidiq,@nerdforge,@Nerdforge,handle,https://vidiq.com/youtube-stats/channel/@Nerdf...,succeeded,None
12,5570,2026-07-23T02:34:57+00:00,vidiq,@theovon,@TheoVon,handle,https://vidiq.com/youtube-stats/channel/@TheoVon,succeeded,None
13,5569,2026-07-23T02:34:39+00:00,vidiq,@johnnyharris,@johnnyharris,handle,https://vidiq.com/youtube-stats/channel/@johnn...,failed,metrics_unavailable
14,5568,2026-07-23T02:34:23+00:00,vidiq,@shawstrength,@SHAWSTRENGTH,handle,https://vidiq.com/youtube-stats/channel/@SHAWS...,failed,metrics_unavailable
15,5567,2026-07-23T02:34:07+00:00,vidiq,@kwtxnews10,@kwtxnews10,handle,https://vidiq.com/youtube-stats/channel/@kwtxn...,succeeded,None
16,5566,2026-07-23T02:33:48+00:00,vidiq,@firstwefeast,@FirstWeFeast,handle,https://vidiq.com/youtube-stats/channel/@First...,failed,metrics_unavailable
17,5565,2026-07-23T02:33:32+00:00,vidiq,@rachplusfive,@RachPlusFive,handle,https://vidiq.com/youtube-stats/channel/@RachP...,succeeded,None
18,5564,2026-07-23T02:33:11+00:00,vidiq,@huskybythegeek,@Huskybythegeek,handle,https://vidiq.com/youtube-stats/channel/@Husky...,succeeded,None
19,5563,2026-07-23T02:32:52+00:00,vidiq,@besmart,@besmart,handle,https://vidiq.com/youtube-stats/channel/@besmart,failed,metrics_unavailable

====================================================================================================
TABLE: collection_errors
====================================================================================================

Schema:

   cid         name     type  notnull dflt_value  pk
0    0           id  INTEGER        0       None   1
1    1  occurred_at     TEXT        1       None   0
2    2       source     TEXT        1       None   0
3    3   channel_id     TEXT        0       None   0
4    4   source_url     TEXT        0       None   0
5    5   error_type     TEXT        1       None   0
6    6  status_code  INTEGER        0       None   0
7    7      message     TEXT        1       None   0

Latest rows:

,id,occurred_at,source,channel_id,source_url,error_type,status_code,message
0,780,2026-07-23T02:38:23+00:00,vidiq,@NicholasLightTV,https://vidiq.com/youtube-stats/channel/@Nicho...,metrics_unavailable,None,vidIQ metrics unavailable.
1,779,2026-07-23T02:38:07+00:00,vidiq,@jeffostroff,https://vidiq.com/youtube-stats/channel/@jeffo...,metrics_unavailable,None,vidIQ metrics unavailable.
2,778,2026-07-23T02:37:33+00:00,vidiq,@chanceshomeworld,https://vidiq.com/youtube-stats/channel/@chanc...,metrics_unavailable,None,vidIQ metrics unavailable.
3,777,2026-07-23T02:36:42+00:00,vidiq,@deenthegreat1,https://vidiq.com/youtube-stats/channel/@deent...,metrics_unavailable,None,vidIQ metrics unavailable.
4,776,2026-07-23T02:36:06+00:00,vidiq,@statn1me,https://vidiq.com/youtube-stats/channel/@statn1me,metrics_unavailable,None,vidIQ metrics unavailable.
5,775,2026-07-23T02:35:50+00:00,vidiq,@ScotsAnimeReaction,https://vidiq.com/youtube-stats/channel/@Scots...,metrics_unavailable,None,vidIQ metrics unavailable.
6,774,2026-07-23T02:34:39+00:00,vidiq,@johnnyharris,https://vidiq.com/youtube-stats/channel/@johnn...,metrics_unavailable,None,vidIQ metrics unavailable.
7,773,2026-07-23T02:34:23+00:00,vidiq,@SHAWSTRENGTH,https://vidiq.com/youtube-stats/channel/@SHAWS...,metrics_unavailable,None,vidIQ metrics unavailable.
8,772,2026-07-23T02:33:48+00:00,vidiq,@FirstWeFeast,https://vidiq.com/youtube-stats/channel/@First...,metrics_unavailable,None,vidIQ metrics unavailable.
9,771,2026-07-23T02:32:52+00:00,vidiq,@besmart,https://vidiq.com/youtube-stats/channel/@besmart,metrics_unavailable,None,vidIQ metrics unavailable.
10,770,2026-07-23T02:32:36+00:00,vidiq,@MandJTV,https://vidiq.com/youtube-stats/channel/@MandJTV,metrics_unavailable,None,vidIQ metrics unavailable.
11,769,2026-07-23T02:31:08+00:00,vidiq,@PitchMeetings,https://vidiq.com/youtube-stats/channel/@Pitch...,metrics_unavailable,None,vidIQ metrics unavailable.
12,768,2026-07-23T02:30:52+00:00,vidiq,@coffeezillaextras,https://vidiq.com/youtube-stats/channel/@coffe...,metrics_unavailable,None,vidIQ metrics unavailable.
13,767,2026-07-23T02:30:36+00:00,vidiq,@CrackingTheCryptic,https://vidiq.com/youtube-stats/channel/@Crack...,metrics_unavailable,None,vidIQ metrics unavailable.
14,766,2026-07-23T02:29:26+00:00,vidiq,UCA61H4fWOMHikLcUFKyQUog,https://vidiq.com/youtube-stats/channel/UCA61H...,metrics_unavailable,None,vidIQ metrics unavailable.
15,765,2026-07-23T02:29:25+00:00,vidiq,UCA61H4fWOMHikLcUFKyQUog,https://vidiq.com/youtube-stats/channel/UCA61H...,metrics_unavailable,None,vidIQ metrics unavailable.
16,764,2026-07-23T02:28:49+00:00,vidiq,@veritasium,https://vidiq.com/youtube-stats/channel/@verit...,metrics_unavailable,None,vidIQ metrics unavailable.
17,763,2026-07-23T02:28:33+00:00,vidiq,@cjya,https://vidiq.com/youtube-stats/channel/@cjya,metrics_unavailable,None,vidIQ metrics unavailable.
18,762,2026-07-23T02:27:58+00:00,vidiq,@OblivionYouTube,https://vidiq.com/youtube-stats/channel/@Obliv...,metrics_unavailable,None,vidIQ metrics unavailable.
19,761,2026-07-23T02:26:47+00:00,vidiq,@MTVUK,https://vidiq.com/youtube-stats/channel/@MTVUK,metrics_unavailable,None,vidIQ metrics unavailable.

====================================================================================================
TABLE: profile_queue
====================================================================================================

Schema:

    cid                             name     type  notnull dflt_value  pk
0     0                      channel_key     TEXT        0       None   1
1     1                       channel_id     TEXT        1       None   0
2     2                     channel_name     TEXT        0       None   0
3     3                  latest_video_at     TEXT        1       None   0
4     4                     last_seen_at     TEXT        1       None   0
5     5                  last_success_at     TEXT        0       None   0
6     6                         digested  INTEGER        1          0   0
7     7                  assigned_source     TEXT        1       None   0
8     8                     vidiq_failed  INTEGER        1          0   0
9     9               socialblade_failed  INTEGER        1          0   0
10   10                     needs_review  INTEGER        1          0   0
11   11                       claimed_by     TEXT        0       None   0
12   12                       claimed_at     TEXT        0       None   0
13   13               youtube_channel_id     TEXT        0       None   0
14   14            channel_id_claimed_by     TEXT        0       None   0
15   15            channel_id_claimed_at     TEXT        0       None   0
16   16  youtube_channel_id_attempted_at     TEXT        0       None   0
17   17               youtube_api_failed  INTEGER        1          0   0
18   18         youtube_api_attempted_at     TEXT        0       None   0
19   19           youtube_api_success_at     TEXT        0       None   0

Latest rows:

,channel_key,channel_id,channel_name,latest_video_at,last_seen_at,last_success_at,digested,assigned_source,vidiq_failed,socialblade_failed,needs_review,claimed_by,claimed_at,youtube_channel_id,channel_id_claimed_by,channel_id_claimed_at,youtube_channel_id_attempted_at,youtube_api_failed,youtube_api_attempted_at,youtube_api_success_at
0,@abcnews,@ABCNews,ABC News,2026-07-23T02:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:01:11+00:00,1,vidiq,1,1,0,None,None,UCBi2mrWuNuyYy4gbM6fU18Q,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:01:11+00:00
1,@airrack,@airrack,Airrack,2026-07-17T07:34:11+00:00,2026-07-23T03:10:39+00:00,2026-07-20T12:12:27+00:00,0,vidiq,0,1,0,vidiq-18270,2026-07-23T02:23:21+00:00,None,None,None,None,1,2026-07-23T02:21:25+00:00,None
2,@akstareng,@AKSTARENG,AKSTAR ENG,2026-04-23T23:57:27+00:00,2026-07-23T03:10:39+00:00,None,1,socialblade,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCIAie1orP_SjI0T591dAUjw,None,None,None,1,2026-07-23T02:54:09+00:00,None
3,@allanwv,@allanwv,allanwv,2009-07-27T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-20T03:21:47+00:00,1,vidiq,0,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCcQQ3J0uzK4GO6BKF7KIYKA,None,None,None,1,2026-07-23T02:54:09+00:00,None
4,@andreijikh,@AndreiJikh,Andrei Jikh,2026-07-21T15:18:55+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:02:18+00:00,1,vidiq,1,1,0,None,None,UCGy7SkBjcIAgTiwkXEtPnYg,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:02:18+00:00
5,@andreipiano,@AndreiPiano,Andrei Piano,2022-07-24T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-20T03:07:04+00:00,1,vidiq,0,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UC6oPj0CXwGi1M280hUW-vyw,None,None,None,1,2026-07-23T02:54:09+00:00,None
6,@annaaaltamirano,@annaaaltamirano,Anna Altamirano,2026-07-20T16:08:02+00:00,2026-07-23T03:10:39+00:00,2026-07-22T05:19:34+00:00,1,vidiq,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCA-0l1VBIG1uTvVeMD_l5kw,None,None,None,1,2026-07-23T02:54:09+00:00,None
7,@asmongoldclips,@AsmongoldClips,Asmongold Clips,2026-07-19T17:33:42+00:00,2026-07-23T03:10:39+00:00,2026-07-22T00:37:52+00:00,0,socialblade,1,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCMwJJL5FJFuTRT55ksbQ4GQ,None,None,2026-07-22T06:08:34+00:00,1,2026-07-23T02:54:09+00:00,None
8,@asmontv,@AsmonTV,Asmongold TV,2026-07-22T23:02:27+00:00,2026-07-23T03:10:39+00:00,2026-07-21T03:01:29+00:00,0,socialblade,1,0,0,socialblade-1718,2026-07-23T01:21:27+00:00,UCQeRaTukNYft1_6AZPACnog,None,None,2026-07-21T03:57:55+00:00,0,None,None
9,@beardmeatsfood,@Beardmeatsfood,BeardMeatsFood,2026-07-19T17:33:42+00:00,2026-07-23T03:10:39+00:00,2026-07-21T06:18:26+00:00,1,vidiq,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCc9CjaAjsMMvaSghZB7-Kog,None,None,None,1,2026-07-23T02:54:09+00:00,None
10,@blueyofficialchannel,@BlueyOfficialChannel,Bluey - Official Channel,2026-07-23T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T02:59:57+00:00,1,socialblade,1,1,0,None,None,UCVzLLZkDuFGAE2BGdBuBNBg,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T02:59:57+00:00
11,@bobross_thejoyofpainting,@bobross_thejoyofpainting,Bob Ross,2017-07-25T01:56:39+00:00,2026-07-23T03:10:39+00:00,2026-07-20T13:41:07+00:00,1,vidiq,0,1,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCxcnsr1R5Ge_fbTu5ajt8DQ,None,None,None,1,2026-07-23T02:54:09+00:00,None
12,@boostedboiz,@boostedboiz,BoostedBoiKyle,2026-07-22T01:56:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:01:29+00:00,1,vidiq,1,1,0,None,None,UC8LsMvKJ-l8a8nASFsuH4Ww,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:01:29+00:00
13,@brysondechambeau,@brysondechambeau,Bryson DeChambeau,2026-07-17T07:34:16+00:00,2026-07-23T03:10:39+00:00,2026-07-20T01:56:49+00:00,1,socialblade,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCCxF55adGXOscJ3L8qdKnrQ,None,None,None,1,2026-07-23T02:54:09+00:00,None
14,@bulwarkmedia,@bulwarkmedia,The Bulwark,2026-07-23T00:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T02:59:53+00:00,1,vidiq,0,1,0,None,None,UCG4Hp1KbGw4e02N7FpPXDgQ,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T02:59:53+00:00
15,@carterkench,@CarterKench,Carter Kench,2026-07-19T07:52:02+00:00,2026-07-23T03:10:39+00:00,2026-07-21T19:12:37+00:00,1,vidiq,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCs0YbZMZhcK1-zlnquUmXzQ,None,None,None,1,2026-07-23T02:54:09+00:00,None
16,@cleetusm,@CleetusM,Cleetus McFarland,2026-07-22T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-22T00:14:37+00:00,0,socialblade,1,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCh8f8vssLddD2PbnU3Ag_Bw,None,None,2026-07-22T01:45:16+00:00,1,2026-07-23T02:54:09+00:00,None
17,@cumtismgambles,@CumtismGambles,Cumtism Gambles,2026-07-21T12:05:06+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:02:23+00:00,1,vidiq,1,1,0,None,None,UCrgta1_fMLqmR0d4J5keyzg,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:02:23+00:00
18,@danny,@danny,Danny Duncan,2026-07-17T07:34:11+00:00,2026-07-23T03:10:39+00:00,2026-07-20T12:13:16+00:00,0,vidiq,0,0,0,vidiq-18270,2026-07-23T02:23:21+00:00,None,None,None,None,1,2026-07-23T02:21:25+00:00,None
19,@donut,@Donut,Donut,2026-07-22T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:01:31+00:00,1,vidiq,1,1,0,None,None,UCL6JmiMXKoXS6bpP1D3bk8g,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:01:31+00:00

====================================================================================================
TABLE: youtube_api_quota_usage
====================================================================================================

Schema:

   cid        name     type  notnull dflt_value  pk
0    0  quota_date     TEXT        0       None   1
1    1  units_used  INTEGER        1          0   0

Latest rows:

   quota_date  units_used
0  2026-07-22        2650

In [9]:
connection.close()

In [16]:
display(preview_table('profile_queue'))

,channel_key,channel_id,channel_name,latest_video_at,last_seen_at,last_success_at,digested,assigned_source,vidiq_failed,socialblade_failed,needs_review,claimed_by,claimed_at,youtube_channel_id,channel_id_claimed_by,channel_id_claimed_at,youtube_channel_id_attempted_at,youtube_api_failed,youtube_api_attempted_at,youtube_api_success_at
0,@abcnews,@ABCNews,ABC News,2026-07-23T02:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:01:11+00:00,1,vidiq,1,1,0,None,None,UCBi2mrWuNuyYy4gbM6fU18Q,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:01:11+00:00
1,@airrack,@airrack,Airrack,2026-07-17T07:34:11+00:00,2026-07-23T03:10:39+00:00,2026-07-20T12:12:27+00:00,0,vidiq,0,1,0,vidiq-18270,2026-07-23T02:23:21+00:00,None,None,None,None,1,2026-07-23T02:21:25+00:00,None
2,@akstareng,@AKSTARENG,AKSTAR ENG,2026-04-23T23:57:27+00:00,2026-07-23T03:10:39+00:00,None,1,socialblade,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCIAie1orP_SjI0T591dAUjw,None,None,None,1,2026-07-23T02:54:09+00:00,None
3,@allanwv,@allanwv,allanwv,2009-07-27T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-20T03:21:47+00:00,1,vidiq,0,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCcQQ3J0uzK4GO6BKF7KIYKA,None,None,None,1,2026-07-23T02:54:09+00:00,None
4,@andreijikh,@AndreiJikh,Andrei Jikh,2026-07-21T15:18:55+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:02:18+00:00,1,vidiq,1,1,0,None,None,UCGy7SkBjcIAgTiwkXEtPnYg,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:02:18+00:00
5,@andreipiano,@AndreiPiano,Andrei Piano,2022-07-24T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-20T03:07:04+00:00,1,vidiq,0,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UC6oPj0CXwGi1M280hUW-vyw,None,None,None,1,2026-07-23T02:54:09+00:00,None
6,@annaaaltamirano,@annaaaltamirano,Anna Altamirano,2026-07-20T16:08:02+00:00,2026-07-23T03:10:39+00:00,2026-07-22T05:19:34+00:00,1,vidiq,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCA-0l1VBIG1uTvVeMD_l5kw,None,None,None,1,2026-07-23T02:54:09+00:00,None
7,@asmongoldclips,@AsmongoldClips,Asmongold Clips,2026-07-19T17:33:42+00:00,2026-07-23T03:10:39+00:00,2026-07-22T00:37:52+00:00,0,socialblade,1,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCMwJJL5FJFuTRT55ksbQ4GQ,None,None,2026-07-22T06:08:34+00:00,1,2026-07-23T02:54:09+00:00,None
8,@asmontv,@AsmonTV,Asmongold TV,2026-07-22T23:02:27+00:00,2026-07-23T03:10:39+00:00,2026-07-21T03:01:29+00:00,0,socialblade,1,0,0,socialblade-1718,2026-07-23T01:21:27+00:00,UCQeRaTukNYft1_6AZPACnog,None,None,2026-07-21T03:57:55+00:00,0,None,None
9,@beardmeatsfood,@Beardmeatsfood,BeardMeatsFood,2026-07-19T17:33:42+00:00,2026-07-23T03:10:39+00:00,2026-07-21T06:18:26+00:00,1,vidiq,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCc9CjaAjsMMvaSghZB7-Kog,None,None,None,1,2026-07-23T02:54:09+00:00,None
10,@blueyofficialchannel,@BlueyOfficialChannel,Bluey - Official Channel,2026-07-23T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T02:59:57+00:00,1,socialblade,1,1,0,None,None,UCVzLLZkDuFGAE2BGdBuBNBg,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T02:59:57+00:00
11,@bobross_thejoyofpainting,@bobross_thejoyofpainting,Bob Ross,2017-07-25T01:56:39+00:00,2026-07-23T03:10:39+00:00,2026-07-20T13:41:07+00:00,1,vidiq,0,1,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCxcnsr1R5Ge_fbTu5ajt8DQ,None,None,None,1,2026-07-23T02:54:09+00:00,None
12,@boostedboiz,@boostedboiz,BoostedBoiKyle,2026-07-22T01:56:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:01:29+00:00,1,vidiq,1,1,0,None,None,UC8LsMvKJ-l8a8nASFsuH4Ww,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:01:29+00:00
13,@brysondechambeau,@brysondechambeau,Bryson DeChambeau,2026-07-17T07:34:16+00:00,2026-07-23T03:10:39+00:00,2026-07-20T01:56:49+00:00,1,socialblade,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCCxF55adGXOscJ3L8qdKnrQ,None,None,None,1,2026-07-23T02:54:09+00:00,None
14,@bulwarkmedia,@bulwarkmedia,The Bulwark,2026-07-23T00:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T02:59:53+00:00,1,vidiq,0,1,0,None,None,UCG4Hp1KbGw4e02N7FpPXDgQ,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T02:59:53+00:00
15,@carterkench,@CarterKench,Carter Kench,2026-07-19T07:52:02+00:00,2026-07-23T03:10:39+00:00,2026-07-21T19:12:37+00:00,1,vidiq,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UCs0YbZMZhcK1-zlnquUmXzQ,None,None,None,1,2026-07-23T02:54:09+00:00,None
16,@cleetusm,@CleetusM,Cleetus McFarland,2026-07-22T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-22T00:14:37+00:00,0,socialblade,1,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCh8f8vssLddD2PbnU3Ag_Bw,None,None,2026-07-22T01:45:16+00:00,1,2026-07-23T02:54:09+00:00,None
17,@cumtismgambles,@CumtismGambles,Cumtism Gambles,2026-07-21T12:05:06+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:02:23+00:00,1,vidiq,1,1,0,None,None,UCrgta1_fMLqmR0d4J5keyzg,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:02:23+00:00
18,@danny,@danny,Danny Duncan,2026-07-17T07:34:11+00:00,2026-07-23T03:10:39+00:00,2026-07-20T12:13:16+00:00,0,vidiq,0,0,0,vidiq-18270,2026-07-23T02:23:21+00:00,None,None,None,None,1,2026-07-23T02:21:25+00:00,None
19,@donut,@Donut,Donut,2026-07-22T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-23T03:01:31+00:00,1,vidiq,1,1,0,None,None,UCL6JmiMXKoXS6bpP1D3bk8g,None,None,None,0,2026-07-23T02:54:09+00:00,2026-07-23T03:01:31+00:00
20,@dreamewaves,@dreamewaves,Relax Waves,2026-06-21T10:46:27+00:00,2026-07-23T03:10:39+00:00,2026-07-20T02:45:26+00:00,1,vidiq,0,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UC8uUQ3nXc9lqVc51Nt0Jrdw,None,None,None,1,2026-07-23T02:54:09+00:00,None
21,@espnfc,@ESPNFC,ESPN FC,2026-07-23T02:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-21T16:56:21+00:00,1,vidiq,1,1,1,youtube-api-24543,2026-07-23T02:54:09+00:00,UC6c1z7bA__85CIWZ_jpCK-Q,None,None,None,1,2026-07-23T02:54:09+00:00,None
22,@fahadbadar2,@fahadbadar2,Fahad Badar,2023-07-24T03:10:39+00:00,2026-07-23T03:10:39+00:00,2026-07-20T03:04:34+00:00,1,vidiq,0,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCBpUcU4ufc4d5zWvsYcahaQ,None,None,None,1,2026-07-23T02:54:09+00:00,None
23,@fallontonight,@fallontonight,The Tonight Show Starring Jimmy Fallon,2026-07-22T04:23:47+00:00,2026-07-23T03:10:39+00:00,2026-07-22T06:39:29+00:00,0,socialblade,1,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UC8-Th83bH_thdKZDJCrn88g,None,None,2026-07-22T07:58:41+00:00,1,2026-07-23T02:54:09+00:00,None
24,@fifa,@fifa,FIFA,2026-07-20T19:38:16+00:00,2026-07-23T03:10:39+00:00,2026-07-20T23:26:14+00:00,0,socialblade,1,0,0,youtube-api-24543,2026-07-23T02:54:09+00:00,UCpcTrCXblq78GZrTUTLWeBw,None,None,2026-07-21T00:54:11+00:00,1,2026-07-23T02:54:09+00:00,None