# Inspect Ingested Data Tables

This notebook helps you inspect the SQLite bronze tables used by Skimmer.

- Default DB path: `data/skimmer.db`
- Override with env var: `SKIMMER_DB_PATH`
- It lists tables, shows schema, row counts, and recent records.

In [9]:
import json
import os
import sqlite3
from pathlib import Path

import pandas as pd
from IPython.display import display


def find_repo_root(start: Path | None = None) -> Path:
    """Locate the repository root so the notebook runs from any working directory."""

    start = (start or Path.cwd()).resolve()
    for candidate in (start, *start.parents):
        if (candidate / 'scripts' / 'RecomendationAnalysis').is_dir() and (candidate / 'data').is_dir():
            return candidate
    raise RuntimeError('Could not locate the skimmer repository root from the current directory.')


# The default database path is repository-relative, so it must not depend on the
# kernel's working directory: this notebook lives in notebooks/, where a bare
# 'data/skimmer.db' resolves to notebooks/data/skimmer.db and does not exist.
REPO_ROOT = find_repo_root()
DEFAULT_DB_PATH = REPO_ROOT / 'data' / 'skimmer.db'
DB_PATH = Path(os.environ.get('SKIMMER_DB_PATH', DEFAULT_DB_PATH)).expanduser()

print(f'Repository root: {REPO_ROOT}')
print(f'Using database: {DB_PATH.resolve()}')
if not DB_PATH.exists():
    raise FileNotFoundError(f'Database not found: {DB_PATH}')

Repository root: /home/orangepi/code_projects/skimmer
Using database: /home/orangepi/code_projects/skimmer/data/skimmer.db

In [10]:
connection = sqlite3.connect(DB_PATH)

tables_df = pd.read_sql_query(
    """
    SELECT name AS table_name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name
    """,
    connection,
)

if tables_df.empty:
    raise RuntimeError('No tables found in the database.')

display(tables_df)

                             table_name
0   bronze_socialblade_channel_profiles
1      bronze_socialblade_channel_stats
2         bronze_vidiq_channel_profiles
3            bronze_vidiq_channel_stats
4                bronze_youtube_skimmed
5       bronze_youtubeapi_channel_stats
6         bronze_youtubeapi_video_stats
7                   collection_attempts
8                     collection_errors
9                discovery_seed_history
10                        profile_queue
11              youtube_api_quota_usage

In [11]:
def table_schema(table_name: str) -> pd.DataFrame:
    return pd.read_sql_query(f"PRAGMA table_info({table_name})", connection)


def row_count(table_name: str) -> int:
    query = f"SELECT COUNT(*) AS row_count FROM {table_name}"
    return int(pd.read_sql_query(query, connection).iloc[0]['row_count'])


def preview_table(table_name: str, limit: int = 25) -> pd.DataFrame:
    schema = table_schema(table_name)
    column_names = schema['name'].tolist()
    order_column = next(
        (
            column
            for column in ('id', 'last_seen_at', 'observed_at', 'occurred_at', 'created_at', 'latest_video_at')
            if column in column_names
        ),
        next((column for column, is_primary_key in zip(schema['name'], schema['pk']) if is_primary_key), None),
    )
    order_by = f' ORDER BY "{order_column}" DESC' if order_column else ''
    query = f'SELECT * FROM "{table_name}"{order_by} LIMIT {int(limit)}'
    df = pd.read_sql_query(query, connection)

    if 'raw_record_json' in df.columns:
        def parse_raw(value):
            if value is None:
                return None
            try:
                return json.loads(value)
            except (json.JSONDecodeError, TypeError):
                return value

        df['raw_record_json_parsed'] = df['raw_record_json'].map(parse_raw)

    return df

In [12]:
summary_rows = []
for table_name in tables_df['table_name'].tolist():
    summary_rows.append({'table_name': table_name, 'row_count': row_count(table_name)})

summary_df = pd.DataFrame(summary_rows).sort_values(['row_count', 'table_name'], ascending=[False, True])
display(summary_df)

                             table_name  row_count
6         bronze_youtubeapi_video_stats     742145
4                bronze_youtube_skimmed     414856
10                        profile_queue      48533
5       bronze_youtubeapi_channel_stats      40256
7                   collection_attempts      19436
3            bronze_vidiq_channel_stats       8448
8                     collection_errors       8049
2         bronze_vidiq_channel_profiles       7128
9                discovery_seed_history        977
1      bronze_socialblade_channel_stats        311
11              youtube_api_quota_usage         14
0   bronze_socialblade_channel_profiles          0

In [6]:
for table_name in tables_df['table_name'].tolist():
    print('\n' + '=' * 100)
    print(f'TABLE: {table_name}')
    print('=' * 100)

    print('\nSchema:')
    display(table_schema(table_name))

    print('\nLatest rows:')
    display(preview_table(table_name, limit=20))

====================================================================================================
TABLE: bronze_socialblade_channel_profiles
====================================================================================================

Schema:

   cid               name     type  notnull dflt_value  pk
0    0                 id  INTEGER        0       None   1
1    1         channel_id     TEXT        1       None   0
2    2       channel_name     TEXT        0       None   0
3    3       channel_type     TEXT        0       None   0
4    4            country     TEXT        0       None   0
5    5         created_at     TEXT        0       None   0
6    6  subscribers_total                 0       None   0
7    7        views_total                 0       None   0
8    8       videos_total                 0       None   0
9    9        data_digest     TEXT        1       None   0

Latest rows:

Empty DataFrame
Columns: [id, channel_id, channel_name, channel_type, country, created_at, subscribers_total, views_total, videos_total, data_digest]
Index: []

====================================================================================================
TABLE: bronze_socialblade_channel_stats
====================================================================================================

Schema:

    cid                name     type  notnull dflt_value  pk
0     0                  id  INTEGER        0       None   1
1     1          channel_id     TEXT        1       None   0
2     2  subscribers_change                 0       None   0
3     3   subscribers_total                 0       None   0
4     4        views_change                 0       None   0
5     5         views_total                 0       None   0
6     6       videos_change                 0       None   0
7     7        videos_total                 0       None   0
8     8        earnings_low                 0       None   0
9     9       earnings_high                 0       None   0
10   10         data_digest     TEXT        1       None   0

Latest rows:

,id,channel_id,subscribers_change,subscribers_total,views_change,views_total,videos_change,videos_total,earnings_low,earnings_high,data_digest
0,311,UCp90hB8_sqLcEEXVgiUCbcw,1000.0,251000,11301,11248718,NaN,377,3,45,430b7ac14efa41886e1a53e8cc17b9192d0d2fb540dabf...
1,310,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,14796,11237417,2.0,377,4,59,6929dab2336ccc2db81c7261cdd7d0b945f585f72db020...
2,309,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,11370,11222621,NaN,375,3,45,6ccebe1db6649eec7fd114d929b677d1befb401d77d645...
3,308,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,19442,11211251,NaN,375,5,78,1f799d2787a707e227bc45ae6fcc7d0ec952acb90fb1f1...
4,307,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,14745,11191809,1.0,375,4,59,93ccf1df46865a2e90d7bce25037bc6729502168ba3c41...
5,306,UCp90hB8_sqLcEEXVgiUCbcw,NaN,250000,17594,11177064,1.0,374,4,70,252d86095d1d2515403d8274ef141f21f89aa93c242482...
6,305,UCp90hB8_sqLcEEXVgiUCbcw,1000.0,250000,20429,11159470,1.0,373,5,82,77cc635d570cf1c159b75639e1f4e084f4acbc6b7dae8a...
7,304,UCp90hB8_sqLcEEXVgiUCbcw,NaN,249000,23942,11139041,2.0,372,6,96,c2c1c3781f2e1886d8ad886a2c36fe2725edf705cf0515...
8,303,UCp90hB8_sqLcEEXVgiUCbcw,NaN,249000,11693,11115099,1.0,370,3,47,05fb8717032356a699c0571ab8023781ec84007f5c2ed8...
9,302,UCp90hB8_sqLcEEXVgiUCbcw,NaN,249000,14035,11103406,NaN,369,4,56,502d2ab81d38c90a273a9dda8910cb2da7d27e1876bbf9...
10,301,UCp90hB8_sqLcEEXVgiUCbcw,NaN,249000,15839,11089371,NaN,369,4,63,e5c6f8241048f778415a4fd0496a8a0d36db77c213695c...
11,300,UCp90hB8_sqLcEEXVgiUCbcw,1000.0,249000,18458,11073532,1.0,369,5,74,582adb96d83e0c93ba3e9308e67439d913bd53d3ebad65...
12,299,UCp90hB8_sqLcEEXVgiUCbcw,NaN,248000,22187,11055074,1.0,368,6,89,e35a2afaaadd47c030d07effa1f3a529f40160e9563d53...
13,298,UCp90hB8_sqLcEEXVgiUCbcw,NaN,248000,24407,11032887,1.0,367,6,98,e817fc8cd35542fc68b46c8677bd4ff4fea10d4eb5a121...
14,297,UC97zsM9Vvmwz0Tmy7-G_pow,1000.0,150000,270511,10744827,22.0,227,68,1100,e69c92160f38c719379ad79235fd499668a3002efab39b...
15,296,UC97zsM9Vvmwz0Tmy7-G_pow,1000.0,149000,1802570,10474316,100.0,205,0,0,7fc72e1c5007807f360325d24e95d249359c00c1d5eed7...
16,295,UC97zsM9Vvmwz0Tmy7-G_pow,2000.0,148000,58196,12276886,68.0,305,0,0,861ec04dcf581beb00f40c349d8c01acde6635f213e068...
17,294,UC97zsM9Vvmwz0Tmy7-G_pow,1000.0,146000,89359,12335082,2.0,237,22,357,97aa603bb6be0930722adf428ee50e626529bc8ff3d776...
18,293,UC97zsM9Vvmwz0Tmy7-G_pow,NaN,145000,1217090,12245723,45.0,239,0,0,09dd6249d650ca39b69a258914fce52f77568af5291bc7...
19,292,UC97zsM9Vvmwz0Tmy7-G_pow,1000.0,145000,1005680,13462813,10.0,194,251,4000,6e99580f3482f656c5bfff2a28387e7218baaf7fba1e54...

====================================================================================================
TABLE: bronze_vidiq_channel_profiles
====================================================================================================

Schema:

    cid                        name     type  notnull dflt_value  pk
0     0                          id  INTEGER        0       None   1
1     1                  channel_id     TEXT        1       None   0
2     2                channel_name     TEXT        0       None   0
3     3                   joined_at     TEXT        0       None   0
4     4                    location     TEXT        0       None   0
5     5                    category     TEXT        0       None   0
6     6                videos_total                 0       None   0
7     7           subscribers_total                 0       None   0
8     8                 views_total                 0       None   0
9     9  estimated_monthly_earnings                 0       None   0
10   10              content_period     TEXT        0       None   0
11   11           long_form_uploads                 0       None   0
12   12              shorts_uploads                 0       None   0
13   13             long_form_views                 0       None   0
14   14                shorts_views                 0       None   0
15   15      ranking_30_day_country     TEXT        0       None   0
16   16    ranking_30_day_worldwide     TEXT        0       None   0
17   17                 data_digest     TEXT        1       None   0

Latest rows:

,id,channel_id,channel_name,joined_at,location,category,videos_total,subscribers_total,views_total,estimated_monthly_earnings,content_period,long_form_uploads,shorts_uploads,long_form_views,shorts_views,ranking_30_day_country,ranking_30_day_worldwide,data_digest
0,6181,UCj9QhyYCvhAwiBHA5B88pYg,ObliviousHD,"Dec 30, 2013",United Kingdom,Gaming,About,4350000,757780000,11000,"Since Jan 01, 2026",None,None,None,None,GB,#262,12640a7b418e02dd3e4d88a3bb64f85cb700cf1a1d12df...
1,6180,UCJ6Njkk8xejCkPQYrizxbcw,Jugar Quiz,"Dec 03, 2015",Unknown,Education,About,133000,9730000,3000,"Since Jan 01, 2026",None,None,None,None,Worldwide,"#523,748",e068d0c4012eb143df7962f30af4ae3b36ab56fa943ada...
2,6179,UCiHXjMD5PRwSbwmecMaUdpw,TUFF Music,"Oct 25, 2020",Unknown,Music,About,372000,280950000,3000,"Since Jan 01, 2026",None,None,None,None,Worldwide,"#202,608",c45e515b762f860026ffea5867f4d303a3169a973f7218...
3,6178,UCiCYF45tN2VrMiUTPLYmeww,June Quiz - Trivia,"Sep 11, 2010",Spain,Sports,About,7340,728400,616,"Since Jan 01, 2026",None,None,None,None,ES,"#41,773",4aacbca603e6284e8d7cb798961b4bc0fc37ab75a92a16...
4,6177,UChiVzeEpJRPT3uB-2VxXMkg,Apex TileX Hop,"Apr 03, 2026",United States,Gaming,About,1520,803590,344,"Since Apr 03, 2026",None,None,None,None,US,"#1,197,651",6d647fb68595dc2115bdb82ab8a47d81be0f839ed1205b...
5,6176,UCh2wQObZKpDDEq8Aje6s8uQ,DeltaScheming,"Jan 21, 2026",United Kingdom,Gaming,About,1230,169150,186,"Since Jan 22, 2026",None,None,None,None,GB,"#184,263",0f43229e04cde95de480538ddb744b4ef22d470f1d5ac6...
6,6175,UCgpkCAVRR1kox06wlHmmGAg,deave1,"Apr 20, 2026",Unknown,Gaming,About,5790,2430000,402,"Since Apr 20, 2026",None,None,None,None,Worldwide,"#5,181,712",65a50bf89a11e7629b38058d9653ca505e377f43ca0339...
7,6174,UCGBETP5G6vRgAe4EvswUvkw,Natural Builder,"Aug 17, 2025",India,Music,About,5860,2810000,39,"Since Jan 01, 2026",None,None,None,None,IN,"#1,034,056",246fa8ee586669459bcadf21bcf8405457cafb013823d4...
8,6173,UCF5g4m-7dwwit9SBqCtVRoA,Spammy,"May 30, 2024",Unknown,Gaming,About,2120,439900,126,"Since Jan 01, 2026",None,None,None,None,Worldwide,"#10,171,670",95ef0fc7971a460ee8522ff710ee9045965e9b30fcecb6...
9,6172,UCeyCm4oNcFaDxA2zmpykqwA,BunnyX_,"Oct 26, 2024",United States,Gaming,About,3810,1130000,24,"Since Jan 01, 2026",None,None,None,None,US,"#753,813",62923d8b015129df92f8308411d0887bee6817a322b3cb...
10,6171,UCErmMCK1sHF-kCtyHpuSXtQ,Kermode and Mayo's Take,"Apr 11, 2022",United Kingdom,Entertainment,About,238000,102020000,2000,"Since Jan 01, 2026",None,None,None,None,GB,"#6,455",2cbe270bcd8e85b0ee78be620bbdf3cd877a3733a84195...
11,6170,UCeCA_YMdjPBWdirWyasIKaA,raghavjuyal creation,"May 20, 2025",India,Entertainment,About,17600,43720000,331,"Since Jan 01, 2026",None,None,None,None,IN,"#522,484",695cb06ef39439a5d6b3a97c5645851a62263fb719b5e1...
12,6169,UCdmTAZii27ueuN3J83XOpgA,Superpixel3D,"Nov 11, 2018",Unknown,Gaming,About,17100,3470000,352,"Since Jan 01, 2026",None,None,None,None,Worldwide,"#2,517,896",b33844bdd650a455dcef00192774f1494401ed1488632a...
13,6168,UCDAhVIHPl1u42dy9GH5vPfQ,bao4wo,"Aug 31, 2019",Unknown,Gaming,About,31800,5770000,1000,"Since Jan 01, 2026",None,None,None,None,Worldwide,"#1,629,621",dc5bac5d6198856d744775b6b44ed57cf1122ee16d13a0...
14,6167,UCcZI214VwwD7SL6fyqm0qrg,AmusingThing,"Jun 08, 2022",Latvia,Gaming,About,55100,7760000,705,"Since Jan 01, 2026",None,None,None,None,🇱🇻,LV,eedb8b3882a23427c618f229d50d933bcc7e6a66c0f635...
15,6166,UCCxYYbEHIL9C-VhfCm9dgig,Aki Do Stuff,"Jul 04, 2019",Unknown,Gaming,About,4810,1630000,34,"Since Jan 01, 2026",None,None,None,None,Worldwide,"#5,983,076",efc1fa78d87bfaabf9f03c21eb7393c5a826d06c3e5539...
16,6165,UCCX1FnlBONCxlqgGaLuoLmw,MS10 CR7⚡️,"Mar 07, 2023",Saudi Arabia,Sports,About,7830,2750000,71,"Since Jan 01, 2026",None,None,None,None,🇸🇦,SA,734040deb730d83bbe2d3216707af643962fd6fe839687...
17,6164,UCcX0VwKvhbfzrPJtlugegBg,EYreacts,"Mar 24, 2021",United States,Entertainment,About,2670000,771290000,26000,"Since Jan 01, 2026",None,None,None,None,US,"#4,669",3eead1ef94188803c7f63347637714ae15a218b623d40e...
18,6163,UCC2-MJJKFKUKDw9DbplYcgQ,Dipper,"Oct 18, 2014",Canada,Gaming,About,3980,618160,169,"Since Jan 01, 2026",None,None,None,None,CA,"#56,677",a8cc563c692e33674129478af2f3de0f5c7e6290d86af5...
19,6162,UCbwUEhxEPnLv1ivS61c15Mw,brokkie,"Mar 02, 2021",France,Gaming,About,2900,116090,17,"Since Jan 01, 2026",None,None,None,None,FR,"#82,627",58c71d591302f7270823f7be8befff2308b10699504167...

====================================================================================================
TABLE: bronze_vidiq_channel_stats
====================================================================================================

Schema:

    cid                name     type  notnull dflt_value  pk
0     0                  id  INTEGER        0       None   1
1     1          channel_id     TEXT        1       None   0
2     2        channel_name     TEXT        0       None   0
3     3         subscribers                 0       None   0
4     4  subscribers_change                 0       None   0
5     5               views                 0       None   0
6     6        views_change                 0       None   0
7     7        earnings_low                 0       None   0
8     8       earnings_high                 0       None   0
9     9          engagement                 0       None   0
10   10    upload_frequency                 0       None   0
11   11      average_length                 0       None   0
12   12         data_digest     TEXT        1       None   0

Latest rows:

,id,channel_id,channel_name,subscribers,subscribers_change,views,views_change,earnings_low,earnings_high,engagement,upload_frequency,average_length,data_digest
0,7501,UCj9QhyYCvhAwiBHA5B88pYg,ObliviousHD,4350000,None,757780000,None,11000,None,None,None,None,2a3a8d5d66ac47922cd393a003e6a86475bb09589a8927...
1,7500,UCJ6Njkk8xejCkPQYrizxbcw,Jugar Quiz,133000,None,9730000,None,3000,None,None,None,None,67c6d9055c7d9efd82a7ef80010f003c742192d0c5e291...
2,7499,UCiHXjMD5PRwSbwmecMaUdpw,TUFF Music,372000,None,280950000,None,3000,None,None,None,None,e64818410743b3c7979149ea5b5a91b98232755b97a86d...
3,7498,UCiCYF45tN2VrMiUTPLYmeww,June Quiz - Trivia,7340,None,728400,None,616,None,None,None,None,51a36e7250d7436101dd2f4a481f6af89b99fd332818d6...
4,7497,UChiVzeEpJRPT3uB-2VxXMkg,Apex TileX Hop,1520,None,803590,None,344,None,None,None,None,a08225e7312690871dd1b386e21ac2ca41017ac71b1f28...
5,7496,UCh2wQObZKpDDEq8Aje6s8uQ,DeltaScheming,1230,None,169150,None,186,None,None,None,None,337e57eaea080310a8e68c87db21606dd1872663f5c66b...
6,7495,UCgpkCAVRR1kox06wlHmmGAg,deave1,5790,None,2430000,None,402,None,None,None,None,06de00097d0e1da34971a0a05e3228b4f2ffe7bf0071b0...
7,7494,UCGBETP5G6vRgAe4EvswUvkw,Natural Builder,5860,None,2810000,None,39,None,None,None,None,f2b5119e742581b6a42e6aa77a1d54fcd5b51244909a40...
8,7493,UCF5g4m-7dwwit9SBqCtVRoA,Spammy,2120,None,439900,None,126,None,None,None,None,2f5c46479f76039270c739962b67f5b90b3c443134ae39...
9,7492,UCeyCm4oNcFaDxA2zmpykqwA,BunnyX_,3810,None,1130000,None,24,None,None,None,None,7c133062460ff0c33eeb9fa482bbf1b666c6f45ca529d6...
10,7491,UCErmMCK1sHF-kCtyHpuSXtQ,Kermode and Mayo's Take,238000,None,102020000,None,2000,None,None,None,None,6c5fd767b497eadfc7c94044c2b7b22311200db7b91174...
11,7490,UCeCA_YMdjPBWdirWyasIKaA,raghavjuyal creation,17600,None,43720000,None,331,None,None,None,None,d41364f59ea01b55afc85f970b5209488bbe94e04fdb70...
12,7489,UCdmTAZii27ueuN3J83XOpgA,Superpixel3D,17100,None,3470000,None,352,None,None,None,None,9af217f1a362023c5adb5e5f500b567e0be89e6866a658...
13,7488,UCDAhVIHPl1u42dy9GH5vPfQ,bao4wo,31800,None,5770000,None,1000,None,None,None,None,01885fb10a9e4c7818b30f4cc94a7121a332eacea7ff91...
14,7487,UCcZI214VwwD7SL6fyqm0qrg,AmusingThing,55100,None,7760000,None,705,None,None,None,None,58871a33f02699ff4a789441b76023cae3108a13224329...
15,7486,UCCxYYbEHIL9C-VhfCm9dgig,Aki Do Stuff,4810,None,1630000,None,34,None,None,None,None,b059b2949a251414954108b7864b10ffa05efbb222ab36...
16,7485,UCCX1FnlBONCxlqgGaLuoLmw,MS10 CR7⚡️,7830,None,2750000,None,71,None,None,None,None,e93ec600224e58a90ca453cb5fa7476bf7ceb14e4a8add...
17,7484,UCcX0VwKvhbfzrPJtlugegBg,EYreacts,2670000,None,771290000,None,26000,None,None,None,None,476ae68e8cee8d493143f470644ca0889247a589ed61aa...
18,7483,UCC2-MJJKFKUKDw9DbplYcgQ,Dipper,3980,None,618160,None,169,None,None,None,None,fe8615def05a3c5b475bb2bdb426bfa19fec89b8499a8f...
19,7482,UCbwUEhxEPnLv1ivS61c15Mw,brokkie,2900,None,116090,None,17,None,None,None,None,9804dd662d98af7580c83ab324957f8bdf5690c914296b...

====================================================================================================
TABLE: bronze_youtube_skimmed
====================================================================================================

Schema:

    cid                  name     type  notnull dflt_value  pk
0     0                    id  INTEGER        0       None   1
1     1           observed_at     TEXT        1       None   0
2     2    video_published_at     TEXT        1       None   0
3     3           source_file     TEXT        1       None   0
4     4            video_name     TEXT        0       None   0
5     5  channel_display_name     TEXT        0       None   0
6     6                 views     TEXT        0       None   0
7     7                   age     TEXT        0       None   0
8     8            channel_id     TEXT        1       None   0
9     9         record_digest     TEXT        1       None   0
10   10    youtube_channel_id     TEXT        0       None   0

Latest rows:

,id,observed_at,video_published_at,source_file,video_name,channel_display_name,views,age,channel_id,record_digest,youtube_channel_id
0,399837,2026-08-05T02:07:45+00:00,2026-08-05T01:07:45+00:00,https://www.youtube.com,"Экстренная посадка самолета в Чикаго, много ра...",БЮРО,18K views,1 hour ago,@buro,45ed25d2608b7b9ea972a5be17fedda88fbeb73fcc8109...,None
1,399836,2026-08-05T02:07:45+00:00,2026-08-02T02:07:45+00:00,https://www.youtube.com,"Trump's catastrophe, voter fury, dem socialism...",CNN,568K views,3 days ago,@CNN,16e05b9256400c3ea4b264b5e86c5ba643b5f463e17fb5...,None
2,399835,2026-08-05T02:07:45+00:00,2026-08-04T22:07:45+00:00,https://www.youtube.com,Harris Faulkner: This is EMBARRASSING!,Fox News,80K views,4 hours ago,@FoxNews,b7050ef8215b8536fa9ec7d6f7eacdb81a1bf07bd65874...,None
3,399834,2026-08-05T02:07:45+00:00,2026-08-04T21:07:45+00:00,https://www.youtube.com,Worst Teammate Ever,Daily Dose Of Internet,191K views,5 hours ago,@DailyDoseOfInternet,989666df1a9d9412f8b4e0d6a1b6652b93f7f2e27682a3...,None
4,399833,2026-08-05T02:07:45+00:00,2026-08-04T02:07:45+00:00,https://www.youtube.com,Darryl Cooper Iran Deep Dive: How the War Will...,Tucker Carlson,409K views,1 day ago,@TuckerCarlson,5e8345f2463af88d59ba35d30188284146e7b8627649cf...,None
5,399832,2026-08-05T02:07:45+00:00,2026-08-02T02:07:45+00:00,https://www.youtube.com,Reckless Ben Interview (Ft. Courtney Love),Channel 5 with Andrew Callaghan,1.2M views,3 days ago,@Channel5YouTube,23808138c173051fd0d980dc095524c5154044005c3d50...,None
6,399831,2026-08-05T02:07:45+00:00,2026-08-04T22:07:45+00:00,https://www.youtube.com,Max Miller defends himself against allegations...,CNN,13K views,4 hours ago,@CNN,52ab2adf414e0dc89763d8d30187a3542ecea1bb0f1f46...,None
7,399830,2026-08-05T02:07:45+00:00,2026-08-04T16:07:45+00:00,https://www.youtube.com,Tony Romo Bodycam is Goofy,penguinz0,589K views,10 hours ago,@penguinz0,17379d84c00a9734c356cb286729b618e3da327b04b84d...,None
8,399829,2026-08-05T02:07:45+00:00,2026-08-03T02:07:45+00:00,https://www.youtube.com,Recreating our Son's Best Memories *Emotional*,The Royalty Family,6.8M views,2 days ago,@royaltyfam,8929c1bf42cd62cb7c84cdcea6c5f80bcb77945a7c5068...,None
9,399828,2026-08-05T02:07:45+00:00,2026-08-04T20:07:45+00:00,https://www.youtube.com,We Opened A Totally Normal Burger Restaurant,SMii7Yplus,445K views,6 hours ago,@SMii7Yplus,358f31ebf31f141fab0ec9b2f36c833ed6cb51eb7a5d54...,None
10,399827,2026-08-05T02:07:45+00:00,2026-08-04T18:07:45+00:00,https://www.youtube.com,Kremlin TV suddenly fears Ukraine’s ballistic ...,TVP WORLD,57K views,8 hours ago,@TVPWorld,4e9169034ec8af1c076838a8f60d2d0ddb451a11983362...,None
11,399826,2026-08-05T02:07:45+00:00,2026-08-02T02:07:45+00:00,https://www.youtube.com,Diamond-encrusted ring becomes new symbol of T...,MS NOW,597K views,3 days ago,@msnow,963b4ac9f87db15f6246e032f525966c4a4e1067f2a0d0...,None
12,399825,2026-08-05T02:07:45+00:00,2026-06-06T02:07:45+00:00,https://www.youtube.com,SQUISHY TRADING My Sister… I SCAMMED Her 😳✅❌,Chillin' with Rachel 💛,3.9M views,2 months ago,@chillinwithrachel,ccd94fb98e55e1fba3d9a1bde037bdef6d7b3d63db9c39...,None
13,399824,2026-08-05T02:07:45+00:00,2026-08-04T19:07:45+00:00,https://www.youtube.com,Russia’s State TV ADMITS Putin’s War is Lost,Jason Jay Smart,86K views,7 hours ago,@JasonJaySmart,ad66a1c3f21262f64f07537f8737904f79f225ca7f0edc...,None
14,399823,2026-08-05T02:07:45+00:00,2026-08-04T19:07:45+00:00,https://www.youtube.com,Ukraine air war takes 'major turn' | Michael C...,Sky News,162K views,7 hours ago,@SkyNews,8d27e99629f6666a56d1527bc62a2afe51f39cd627daa4...,None
15,399822,2026-08-05T02:07:45+00:00,2026-08-05T02:07:45+00:00,https://www.youtube.com,Funeral of Glen Hansard in Dublin | RTÉ News,RTÉ News,196K views,Streamed 11 hours ago,@rtenews,e490896e48193e568a02729a0843080de25952e0669cc2...,None
16,399821,2026-08-05T02:07:45+00:00,2026-07-31T02:07:45+00:00,https://www.youtube.com,Thursday Commute: RM 620 to Manor Rd via I-35 ...,Commuter Chris,953 views,5 days ago,@commuterchris0916,8e0f9578c83791e689aab8cf28d0fce6593a3126ba9e33...,None
17,399820,2026-08-05T02:07:45+00:00,2026-08-01T02:07:45+00:00,https://www.youtube.com,Everything AI Does When You Ask It to Start a ...,Genspark AI,910K views,4 days ago,@GensparkAIOfficial,4e5c2953ec0471c34db006ec25ad6289d849925a28b23f...,None
18,399819,2026-08-05T02:07:45+00:00,2026-08-04T14:07:45+00:00,https://www.youtube.com,"Finally, The Greatest SXS Ever…",Cleetus McFarland,516K views,12 hours ago,@CleetusM,722c213c9dd666def768244404053f01eb1aea8a53d6e5...,None
19,399818,2026-08-05T02:07:45+00:00,2026-07-30T02:07:45+00:00,https://www.youtube.com,Softball elimination game kept getting crazier...,Jomboy Media,499K views,6 days ago,@JomboyMedia,55453cdb3b80b4891afdefd1f953022d99e28a713297ce...,None

====================================================================================================
TABLE: bronze_youtubeapi_channel_stats
====================================================================================================

Schema:

    cid                  name     type  notnull dflt_value  pk
0     0                    id  INTEGER        0       None   1
1     1          collected_at     TEXT        1       None   0
2     2            channel_id     TEXT        1       None   0
3     3          channel_name     TEXT        0       None   0
4     4           subscribers                 0       None   0
5     5    subscribers_change                 0       None   0
6     6                 views                 0       None   0
7     7          views_change                 0       None   0
8     8           video_count                 0       None   0
9     9               country     TEXT        0       None   0
10   10  channel_published_at     TEXT        0       None   0
11   11   uploads_playlist_id     TEXT        0       None   0
12   12           data_digest     TEXT        1       None   0

Latest rows:

,id,collected_at,channel_id,channel_name,subscribers,subscribers_change,views,views_change,video_count,country,channel_published_at,uploads_playlist_id,data_digest
0,40256,2026-08-04T06:50:06+00:00,UCy5qlXmZxyIzVl3ZkbAfh5Q,Aventuras de Fire Spike,101000,None,39414525,None,61,US,2025-04-09T14:00:29.135936Z,UUy5qlXmZxyIzVl3ZkbAfh5Q,94ad0aacccb56e06551ce845ab99a60e82e99f96bc1577...
1,40255,2026-08-04T06:50:06+00:00,UCUmurQDaLLCc6xkGBnngF1w,Lofi Song10,603,None,429502,None,90,None,2026-02-04T16:24:41.151762Z,UUUmurQDaLLCc6xkGBnngF1w,2bbf867d6f0a03bcad0aa5f6000e607b623b513fb3f872...
2,40254,2026-08-04T06:50:06+00:00,UCoyQlGZqKfQGAMZOP_-ECkQ,DX__GROUP__12,109,None,37929,None,51,None,2026-06-08T05:36:18.971626Z,UUoyQlGZqKfQGAMZOP_-ECkQ,864638e553956a7d9b52af2fd3bda6a313e30276a26bca...
3,40253,2026-08-04T06:50:06+00:00,UCi8te23Z2JPmoNyaciG4HDQ,Sayfu20,1160,None,487678,None,98,IO,2026-06-19T08:00:39.831696Z,UUi8te23Z2JPmoNyaciG4HDQ,77c8031ba0bc58dd77ff6eb7e61c4252f63d1e7fe091e6...
4,40252,2026-08-04T06:50:06+00:00,UCfYr45Dmu-JGT3vl_whYaSw,Bima Bernyanyi,170000,None,137434101,None,105,ID,2025-09-04T06:34:22.012425Z,UUfYr45Dmu-JGT3vl_whYaSw,d30397ad1386f432d8e5604bf779f04656bcacbd7c3d91...
5,40251,2026-08-04T06:50:06+00:00,UCEIvLjRoadOgQt7dm-mE0UQ,ᏒᴅX_gaming 50k,367,None,204912,None,21,None,2025-08-10T16:54:43.751301Z,UUEIvLjRoadOgQt7dm-mE0UQ,c36f97e67df5fa13e058733ed5e51679337462da8b0c49...
6,40250,2026-08-04T06:50:06+00:00,UC_0QiEsuXq1SaTHwU_KwtRQ,KiDuMi Portuguese,347,None,127982,None,51,PT,2026-07-08T14:59:31.751777Z,UU_0QiEsuXq1SaTHwU_KwtRQ,87a524936cf1a58465834796c56262f265571011bd66e6...
7,40249,2026-08-04T06:50:06+00:00,UCd_HzIy7rlkNBqyJV80m7ZQ,NEW LO-FI SONG 10k,331,None,98087,None,36,IN,2026-07-12T07:32:27.254089Z,UUd_HzIy7rlkNBqyJV80m7ZQ,5b0f6d71896b3c8346d09b888ce9039c2410183ae177d4...
8,40248,2026-08-04T06:50:06+00:00,UCTxTz5zj19WlI4_7bNaMJtg,Prashant Kumar,1200,None,821480,None,18,None,2026-05-31T10:08:58.350682Z,UUTxTz5zj19WlI4_7bNaMJtg,6de57e9c31374be0e0d442cd259d71b56ea0efc03360f8...
9,40247,2026-08-04T06:50:06+00:00,UClH95at5RKcbI9RzwTE3MKw,HR PATHAN VLOGER,72,None,43765,None,25,None,2026-07-05T04:36:59.6379Z,UUlH95at5RKcbI9RzwTE3MKw,38e8a1d28eeb109468f2eef6aa870d8299059f50cfc03a...
10,40246,2026-08-04T06:50:06+00:00,UChGdWMUf3NifrYpekz_82FQ,Bas gaming 2.3M,84,None,109707,None,79,None,2026-07-08T09:04:21.559272Z,UUhGdWMUf3NifrYpekz_82FQ,d820dd64c8da766654f81069f0c675f1b7a9b697fa51b5...
11,40245,2026-08-04T06:50:06+00:00,UC8ail1tFEVWpLPjnJlTLN9A,León Picarón In het Nederlands,2720,None,655413,None,247,NL,2026-03-12T21:13:41.342238Z,UU8ail1tFEVWpLPjnJlTLN9A,d41b71a658267634b4d675a5031ae5b94f4eea0f78decd...
12,40244,2026-08-04T06:50:06+00:00,UCPxPJX1QG7Odr43g0SxSElg,Barbaad aadmi,63,None,65883,None,49,None,2026-06-17T05:37:34.037508Z,UUPxPJX1QG7Odr43g0SxSElg,c2fe02551aa7e677a2f16c6761838c0aba34e64fadc2c4...
13,40243,2026-08-04T06:50:06+00:00,UC_xnIG9CIYmn7ZjjQkaeKOw,KiDuMi,518,None,113442,None,51,US,2026-07-08T13:34:27.444134Z,UU_xnIG9CIYmn7ZjjQkaeKOw,d3c752fa6b9673a77cb14b984dd4a41c06a78a09210136...
14,40242,2026-08-04T06:50:06+00:00,UC6CAGN8qlebIAolzRcXUxWA,Music + Gaming,1300,None,1552764,None,122,IN,2021-01-27T05:22:27.140326Z,UU6CAGN8qlebIAolzRcXUxWA,f4bc8f703db3b23a8361046b6f1076d02748cc5a808d9d...
15,40241,2026-08-04T06:50:06+00:00,UCY4BdQhPyDWi_DSir2P1b-w,De Avonturen van Slav,7450,None,1168901,None,31,NL,2026-03-31T15:49:47.198609Z,UUY4BdQhPyDWi_DSir2P1b-w,b7405c1611f35b9f779f26c617131e5c2c5164e9384e83...
16,40240,2026-08-04T06:50:06+00:00,UCACxPmL8Q_1C2xd6zyHDGig,GL Best Power,61200,None,4139563,None,33,GR,2020-01-06T18:04:34.530318Z,UUACxPmL8Q_1C2xd6zyHDGig,4a130c5e7fabda9e552028ebb6d11e5a88f516919f56c7...
17,40239,2026-08-04T06:50:06+00:00,UC71Kjh8D1KQ0dvaXijqmwNA,Lunar Vibes Chan,1250,None,237158,None,12,US,2026-06-05T03:33:30.727156Z,UU71Kjh8D1KQ0dvaXijqmwNA,66640304923889d290d49796fb23cbfdebc023e86b6fb7...
18,40238,2026-08-04T06:50:06+00:00,UCllfR4IUx_71dShepiW7zQw,Bonbon World,6720,None,2779898,None,53,US,2026-01-27T09:47:02.353298Z,UUllfR4IUx_71dShepiW7zQw,82a260038062aef1d6daea91c17f45b524532e408ad8ab...
19,40237,2026-08-04T06:50:06+00:00,UCB_dXBobofzxArTDRodZ06w,Multi DO Top Malaysia,2830,None,1277107,None,38,MY,2025-11-14T10:44:12.850073Z,UUB_dXBobofzxArTDRodZ06w,46f4b0106fa1283903c05b0921ab1507f8983e37f21515...

====================================================================================================
TABLE: bronze_youtubeapi_video_stats
====================================================================================================

Schema:

    cid                    name     type  notnull dflt_value  pk
0     0                      id  INTEGER        0       None   1
1     1            collected_at     TEXT        1       None   0
2     2                video_id     TEXT        1       None   0
3     3              channel_id     TEXT        1       None   0
4     4                   title     TEXT        0       None   0
5     5            published_at     TEXT        0       None   0
6     6        duration_seconds                 0       None   0
7     7             category_id     TEXT        0       None   0
8     8                   views                 0       None   0
9     9                   likes                 0       None   0
10   10                comments                 0       None   0
11   11             data_digest     TEXT        1       None   0
12   12  default_audio_language     TEXT        0       None   0
13   13        default_language     TEXT        0       None   0

Latest rows:

,id,collected_at,video_id,channel_id,title,published_at,duration_seconds,category_id,views,likes,comments,data_digest,default_audio_language,default_language
0,742145,2026-08-04T07:54:07+00:00,s5JSigXAMIQ,UCUmurQDaLLCc6xkGBnngF1w,#TohPhirAao #Awarapan #EmraanHashmi #MustafaZa...,2026-07-05T15:29:33Z,17,22,215,4,0,960d4868a3859f2301d07e98c893b7f6f2ca8cab82da9c...,None,None
1,742144,2026-08-04T07:54:07+00:00,zGMfaTalbyw,UCUmurQDaLLCc6xkGBnngF1w,#Dawood #SidhuMooseWala#PunjabiSong #PunjabiMu...,2026-07-07T13:21:01Z,216,22,195981,1282,32,cc3955b50ff37b46825c3e9a7f50236b113468dc1b712e...,None,None
2,742143,2026-08-04T07:54:07+00:00,u4doh8Qe_R4,UCUmurQDaLLCc6xkGBnngF1w,#youtubeshorts #song #digitalcreator #lovesong...,2026-07-09T16:24:51Z,15,22,178,4,0,498ad50b3c18b810965ba40f2a23716394c261cdfa7d95...,None,None
3,742142,2026-08-04T07:54:07+00:00,L13dwXhKvx8,UCUmurQDaLLCc6xkGBnngF1w,#JaiyeSajana #DhurandharTheRevenge #RanveerSin...,2026-07-10T13:03:26Z,152,22,26547,53,1,85fe38bd258255482af948ae84782170885bdf4b267f7f...,None,None
4,742141,2026-08-04T07:54:07+00:00,nEaoUyhLDJg,UCUmurQDaLLCc6xkGBnngF1w,#viral #virel #unboxing #unboxing #entertainment,2026-07-10T17:13:16Z,12,22,111,2,0,9ceec11b112ad8d076478278ec3814234562c62f627ad4...,None,None
5,742140,2026-08-04T07:54:07+00:00,v6PSskBSbwk,UCUmurQDaLLCc6xkGBnngF1w,#Majboor #Saiyaara #Afusic #ZohaWaseem #Shreya...,2026-07-12T03:10:59Z,252,22,58,3,0,02348b20b4c2802f98c09b34644720cfcfe1eccca0d6f6...,None,None
6,742139,2026-08-04T07:54:07+00:00,Q78QkwpFajE,UCUmurQDaLLCc6xkGBnngF1w,#PagliBhulaiyaToSamari #BhojpuriSong #Bhojpuri...,2026-07-12T07:40:18Z,226,22,13,3,1,2f2fc1f39a7c856dbd91a3d80ffaa6367c78ce3fdc9dbd...,None,None
7,742138,2026-08-04T07:54:07+00:00,AZW_flDA1TI,UCUmurQDaLLCc6xkGBnngF1w,#IshqDeFanniar #ColorOfRanjheya #SlowedReverb#...,2026-07-13T13:33:04Z,190,22,57,2,0,a2c43ebbc72a08ac6424e1980021110a9884afc24dd144...,None,None
8,742137,2026-08-04T07:54:07+00:00,fO2MudHTRDc,UCUmurQDaLLCc6xkGBnngF1w,#295 #SidhuMooseWala #TheKidd #Moosetape #Punj...,2026-07-13T16:42:37Z,273,22,56543,281,7,44cdae117039680c4a38da0c35a36344447a6961cfc515...,None,None
9,742136,2026-08-04T07:54:07+00:00,cV6KbR43tUs,UCUmurQDaLLCc6xkGBnngF1w,Hashtags: #DeewaanaDeewaana #ARRahman #TereIsh...,2026-07-14T13:32:27Z,406,22,45,5,1,a3dcfc068daae0c06816d0143f30c6621d8a49b3c6cf2e...,None,None
10,742135,2026-08-04T07:54:07+00:00,LXdh5F3TP9E,UCUmurQDaLLCc6xkGBnngF1w,Hashtags: #YouTubeLive #LiveStream #LiveNow #S...,2026-07-14T17:11:18Z,32,22,17,4,0,da5d96124780816c37129b8c7319c7074d8e1fe0074839...,None,None
11,742134,2026-08-04T07:54:07+00:00,-Q0WWjnMSTM,UCUmurQDaLLCc6xkGBnngF1w,#viral #virel #viralvideo #viralshorts #viralr...,2026-07-14T17:34:14Z,38,22,91,4,0,7194aedff0f6035f0b5c24d3dcd1a7d94ed04979a47be7...,None,None
12,742133,2026-08-04T07:54:07+00:00,AwkqfGIaTzM,UCUmurQDaLLCc6xkGBnngF1w,#Kalyani #Saiyaara #ShreyaGhoshal #SajniRe #Pe...,2026-07-15T14:22:05Z,407,22,73,2,0,3f2ef76e3a0a5d4124c1f2d448537ad594b610a178c099...,None,None
13,742132,2026-08-04T07:54:07+00:00,8lr1rrK9LJ0,UCUmurQDaLLCc6xkGBnngF1w,#PindanDeJaye#SajjanAdeeb#PunjabiSongs #Punjab...,2026-07-16T10:30:50Z,298,22,6413,35,1,439db30d98bff72e86702a70ac7be0bc0e0016459aa230...,None,None
14,742131,2026-08-04T07:54:07+00:00,9tO2Ou9Mvos,UCUmurQDaLLCc6xkGBnngF1w,#SidhuMooseWala #Devil #PBX1 #BygByrd #Punjabi...,2026-07-17T15:39:51Z,264,22,29313,187,3,4684ce2712681831497ad2a5c9ed6c561f3a2001c5e9ec...,None,None
15,742130,2026-08-04T07:54:07+00:00,WeM3DbdbvVU,UCUmurQDaLLCc6xkGBnngF1w,#PaironMeinBandhanHai #Mohabbatein #ShahRukhKh...,2026-07-18T16:26:39Z,131,22,34,2,1,189e61a283bcb61c1466cad8bd963792615448da1ad1aa...,None,None
16,742129,2026-08-04T07:54:07+00:00,775oXMND5EY,UCUmurQDaLLCc6xkGBnngF1w,#LoveSong #IshqTera #GuruRandhawa #RomanticSon...,2026-07-19T07:39:09Z,271,22,32,2,0,4ab79691cd06ba2977deabdc03de760192591c25a81e6c...,None,None
17,742128,2026-08-04T07:54:07+00:00,PTGqBk8eKJ0,UCUmurQDaLLCc6xkGBnngF1w,#Khairiyat #Chhichhore #ArijitSingh #Pritam #A...,2026-07-21T14:49:32Z,281,22,100,1,0,180a3d33529e16f8e570cb80104b6c0c58ad609af947c3...,None,None
18,742127,2026-08-04T07:54:07+00:00,xEvNdw2m5i8,UCUmurQDaLLCc6xkGBnngF1w,#SoorajHiChhaonBanke #Salaar #Prabhas #Prithvi...,2026-07-22T11:59:43Z,235,22,20,7,0,00ac58039414c3260a9f56f87b6a9ecf845688f541b621...,None,None
19,742126,2026-08-04T07:54:07+00:00,aSi4a3nFUtA,UCUmurQDaLLCc6xkGBnngF1w,#SidhuMooseWala #GOAT#Moosetape #WazirPatar #S...,2026-07-23T12:17:07Z,289,22,1568,13,0,ba58d02b099e7f09163f988366a3268b2a5e89198f5749...,None,None

====================================================================================================
TABLE: collection_attempts
====================================================================================================

Schema:

   cid             name     type  notnull dflt_value  pk
0    0               id  INTEGER        0       None   1
1    1      occurred_at     TEXT        1       None   0
2    2           source     TEXT        1       None   0
3    3      channel_key     TEXT        1       None   0
4    4       identifier     TEXT        1       None   0
5    5  identifier_kind     TEXT        1       None   0
6    6       source_url     TEXT        1       None   0
7    7          outcome     TEXT        1       None   0
8    8     failure_type     TEXT        0       None   0

Latest rows:

,id,occurred_at,source,channel_key,identifier,identifier_kind,source_url,outcome,failure_type
0,16955,2026-08-05T02:26:48+00:00,vidiq,ucj9qhyycvhawibha5b88pyg,UCj9QhyYCvhAwiBHA5B88pYg,channel_id,https://vidiq.com/youtube-stats/channel/UCj9Qh...,succeeded,None
1,16954,2026-08-05T02:26:45+00:00,vidiq,ucj9qhyycvhawibha5b88pyg,UCj9QhyYCvhAwiBHA5B88pYg,handle,https://vidiq.com/youtube-stats/channel/UCj9Qh...,failed,metrics_unavailable
2,16953,2026-08-05T02:26:29+00:00,vidiq,ucj6njkk8xejckpqyrizxbcw,UCJ6Njkk8xejCkPQYrizxbcw,channel_id,https://vidiq.com/youtube-stats/channel/UCJ6Nj...,succeeded,None
3,16952,2026-08-05T02:26:26+00:00,vidiq,ucj6njkk8xejckpqyrizxbcw,UCJ6Njkk8xejCkPQYrizxbcw,handle,https://vidiq.com/youtube-stats/channel/UCJ6Nj...,failed,metrics_unavailable
4,16951,2026-08-05T02:26:08+00:00,vidiq,ucixnpc-e_cpvtg1_qm937yw,UCixNpc-e_cpvTg1_qM937Yw,channel_id,https://vidiq.com/youtube-stats/channel/UCixNp...,failed,page_load_timeout
5,16950,2026-08-05T02:25:38+00:00,vidiq,ucixnpc-e_cpvtg1_qm937yw,UCixNpc-e_cpvTg1_qM937Yw,handle,https://vidiq.com/youtube-stats/channel/UCixNp...,failed,page_load_timeout
6,16949,2026-08-05T02:24:51+00:00,vidiq,uciknx0timykggqqznhr1xig,UCiKNX0TIMyKgGqQznhR1Xig,channel_id,https://vidiq.com/youtube-stats/channel/UCiKNX...,failed,metrics_unavailable
7,16948,2026-08-05T02:24:50+00:00,vidiq,uciknx0timykggqqznhr1xig,UCiKNX0TIMyKgGqQznhR1Xig,handle,https://vidiq.com/youtube-stats/channel/UCiKNX...,failed,metrics_unavailable
8,16947,2026-08-05T02:24:33+00:00,vidiq,ucihxjmd5prwsbwmecmaudpw,UCiHXjMD5PRwSbwmecMaUdpw,handle,https://vidiq.com/youtube-stats/channel/UCiHXj...,succeeded,None
9,16946,2026-08-05T02:24:15+00:00,vidiq,ucicyf45tn2vrmiutplymeww,UCiCYF45tN2VrMiUTPLYmeww,channel_id,https://vidiq.com/youtube-stats/channel/UCiCYF...,succeeded,None
10,16945,2026-08-05T02:24:12+00:00,vidiq,ucicyf45tn2vrmiutplymeww,UCiCYF45tN2VrMiUTPLYmeww,handle,https://vidiq.com/youtube-stats/channel/UCiCYF...,failed,metrics_unavailable
11,16944,2026-08-05T02:23:55+00:00,vidiq,uchow5pcfafwr1b-pxfmt9xa,UCHOW5pCfafWR1B-PxFMt9XA,channel_id,https://vidiq.com/youtube-stats/channel/UCHOW5...,failed,page_load_timeout
12,16943,2026-08-05T02:23:24+00:00,vidiq,uchow5pcfafwr1b-pxfmt9xa,UCHOW5pCfafWR1B-PxFMt9XA,handle,https://vidiq.com/youtube-stats/channel/UCHOW5...,failed,page_load_timeout
13,16942,2026-08-05T02:22:38+00:00,vidiq,uchivzeepjrpt3ub-2vxxmkg,UChiVzeEpJRPT3uB-2VxXMkg,handle,https://vidiq.com/youtube-stats/channel/UChiVz...,succeeded,None
14,16941,2026-08-05T02:22:19+00:00,vidiq,uchfrs_e7utjdcoetsxkx7gq,UChfrs_E7uTjdcoetSXKX7gQ,channel_id,https://vidiq.com/youtube-stats/channel/UChfrs...,failed,page_load_timeout
15,16940,2026-08-05T02:21:48+00:00,vidiq,uchfrs_e7utjdcoetsxkx7gq,UChfrs_E7uTjdcoetSXKX7gQ,handle,https://vidiq.com/youtube-stats/channel/UChfrs...,failed,page_load_timeout
16,16939,2026-08-05T02:21:02+00:00,vidiq,uch2wqobzkpddeq8aje6s8uq,UCh2wQObZKpDDEq8Aje6s8uQ,handle,https://vidiq.com/youtube-stats/channel/UCh2wQ...,succeeded,None
17,16938,2026-08-05T02:20:43+00:00,vidiq,ucgpkcavrr1kox06wlhmmgag,UCgpkCAVRR1kox06wlHmmGAg,handle,https://vidiq.com/youtube-stats/channel/UCgpkC...,succeeded,None
18,16937,2026-08-05T02:20:24+00:00,vidiq,ucgbetp5g6vrgae4evswuvkw,UCGBETP5G6vRgAe4EvswUvkw,channel_id,https://vidiq.com/youtube-stats/channel/UCGBET...,succeeded,None
19,16936,2026-08-05T02:20:21+00:00,vidiq,ucgbetp5g6vrgae4evswuvkw,UCGBETP5G6vRgAe4EvswUvkw,handle,https://vidiq.com/youtube-stats/channel/UCGBET...,failed,metrics_unavailable

====================================================================================================
TABLE: collection_errors
====================================================================================================

Schema:

   cid         name     type  notnull dflt_value  pk
0    0           id  INTEGER        0       None   1
1    1  occurred_at     TEXT        1       None   0
2    2       source     TEXT        1       None   0
3    3   channel_id     TEXT        0       None   0
4    4   source_url     TEXT        0       None   0
5    5   error_type     TEXT        1       None   0
6    6  status_code  INTEGER        0       None   0
7    7      message     TEXT        1       None   0

Latest rows:

,id,occurred_at,source,channel_id,source_url,error_type,status_code,message
0,6500,2026-08-05T02:26:45+00:00,vidiq,UCj9QhyYCvhAwiBHA5B88pYg,https://vidiq.com/youtube-stats/channel/UCj9Qh...,metrics_unavailable,None,vidIQ metrics unavailable.
1,6499,2026-08-05T02:26:26+00:00,vidiq,UCJ6Njkk8xejCkPQYrizxbcw,https://vidiq.com/youtube-stats/channel/UCJ6Nj...,metrics_unavailable,None,vidIQ metrics unavailable.
2,6498,2026-08-05T02:26:08+00:00,vidiq,UCixNpc-e_cpvTg1_qM937Yw,https://vidiq.com/youtube-stats/channel/UCixNp...,page_load_timeout,None,vidIQ page load timeout.
3,6497,2026-08-05T02:25:38+00:00,vidiq,UCixNpc-e_cpvTg1_qM937Yw,https://vidiq.com/youtube-stats/channel/UCixNp...,page_load_timeout,None,vidIQ page load timeout.
4,6496,2026-08-05T02:24:51+00:00,vidiq,UCiKNX0TIMyKgGqQznhR1Xig,https://vidiq.com/youtube-stats/channel/UCiKNX...,metrics_unavailable,None,vidIQ metrics unavailable.
5,6495,2026-08-05T02:24:50+00:00,vidiq,UCiKNX0TIMyKgGqQznhR1Xig,https://vidiq.com/youtube-stats/channel/UCiKNX...,metrics_unavailable,None,vidIQ metrics unavailable.
6,6494,2026-08-05T02:24:12+00:00,vidiq,UCiCYF45tN2VrMiUTPLYmeww,https://vidiq.com/youtube-stats/channel/UCiCYF...,metrics_unavailable,None,vidIQ metrics unavailable.
7,6493,2026-08-05T02:23:55+00:00,vidiq,UCHOW5pCfafWR1B-PxFMt9XA,https://vidiq.com/youtube-stats/channel/UCHOW5...,page_load_timeout,None,vidIQ page load timeout.
8,6492,2026-08-05T02:23:24+00:00,vidiq,UCHOW5pCfafWR1B-PxFMt9XA,https://vidiq.com/youtube-stats/channel/UCHOW5...,page_load_timeout,None,vidIQ page load timeout.
9,6491,2026-08-05T02:22:19+00:00,vidiq,UChfrs_E7uTjdcoetSXKX7gQ,https://vidiq.com/youtube-stats/channel/UChfrs...,page_load_timeout,None,vidIQ page load timeout.
10,6490,2026-08-05T02:21:48+00:00,vidiq,UChfrs_E7uTjdcoetSXKX7gQ,https://vidiq.com/youtube-stats/channel/UChfrs...,page_load_timeout,None,vidIQ page load timeout.
11,6489,2026-08-05T02:20:21+00:00,vidiq,UCGBETP5G6vRgAe4EvswUvkw,https://vidiq.com/youtube-stats/channel/UCGBET...,metrics_unavailable,None,vidIQ metrics unavailable.
12,6488,2026-08-05T02:20:03+00:00,vidiq,UCF_tKy-7oGsBPqDIaGdIEqg,https://vidiq.com/youtube-stats/channel/UCF_tK...,page_load_timeout,None,vidIQ page load timeout.
13,6487,2026-08-05T02:19:32+00:00,vidiq,UCF_tKy-7oGsBPqDIaGdIEqg,https://vidiq.com/youtube-stats/channel/UCF_tK...,page_load_timeout,None,vidIQ page load timeout.
14,6486,2026-08-05T02:18:43+00:00,vidiq,UCF5g4m-7dwwit9SBqCtVRoA,https://vidiq.com/youtube-stats/channel/UCF5g4...,metrics_unavailable,None,vidIQ metrics unavailable.
15,6485,2026-08-05T02:17:31+00:00,vidiq,UCe6ZXWAH_l9CSmc1HJ5C-Ig,https://vidiq.com/youtube-stats/channel/UCe6ZX...,page_load_timeout,None,vidIQ page load timeout.
16,6484,2026-08-05T02:17:00+00:00,vidiq,UCe6ZXWAH_l9CSmc1HJ5C-Ig,https://vidiq.com/youtube-stats/channel/UCe6ZX...,page_load_timeout,None,vidIQ page load timeout.
17,6483,2026-08-05T02:14:36+00:00,vidiq,UCcX0VwKvhbfzrPJtlugegBg,https://vidiq.com/youtube-stats/channel/UCcX0V...,metrics_unavailable,None,vidIQ metrics unavailable.
18,6482,2026-08-05T02:13:42+00:00,vidiq,UCbtN9Yq8rBtpwMQxL2U4HuA,https://vidiq.com/youtube-stats/channel/UCbtN9...,page_load_timeout,None,vidIQ page load timeout.
19,6481,2026-08-05T02:13:11+00:00,vidiq,UCbtN9Yq8rBtpwMQxL2U4HuA,https://vidiq.com/youtube-stats/channel/UCbtN9...,page_load_timeout,None,vidIQ page load timeout.

====================================================================================================
TABLE: discovery_seed_history
====================================================================================================

Schema:

   cid                 name     type  notnull dflt_value  pk
0    0                   id  INTEGER        0       None   1
1    1          selected_at     TEXT        1       None   0
2    2             selector     TEXT        1       None   0
3    3        seed_video_id     TEXT        1       None   0
4    4      seed_channel_id     TEXT        1       None   0
5    5                score     REAL        1       None   0
6    6  discovered_channels  INTEGER        1          0   0

Latest rows:

,id,selected_at,selector,seed_video_id,seed_channel_id,score,discovered_channels
0,939,2026-08-05T02:26:34+00:00,high_views_per_subscriber,inwRHM-qOA8,UCHbA5z9GV2Bk0-oKe55aKuQ,1447.964989,24
1,938,2026-08-05T02:26:15+00:00,high_views_per_subscriber,Zqq__DdYpr0,UCjwkE6JlR3ow8TJH-RwOJag,1634.921233,13
2,937,2026-08-05T02:07:27+00:00,high_views_per_subscriber,kmXD_ZtNXqQ,UCwCzQayWzmzKLqstw7B61GA,296.325301,30
3,936,2026-08-05T02:07:12+00:00,high_views_per_subscriber,qIEkxj-u9oQ,UC1AYdm7ZEpPl3TsU7DT5J-w,296.934783,74
4,935,2026-08-05T01:47:26+00:00,high_views_per_subscriber,WTKT4R7X5uU,UCaRoAkoyj1fIu8ZlkD4qnHg,298.056478,18
5,934,2026-08-05T01:47:10+00:00,high_views_per_subscriber,LqMlGKRl88g,UCpN7p4NjZmzc0mxzGQWOhKQ,298.440000,35
6,933,2026-08-05T01:27:14+00:00,high_views_per_subscriber,F-eTgupuFPI,UCaPdA3A0bknjlKRxbLgO27Q,299.567619,15
7,932,2026-08-05T01:26:27+00:00,high_views_per_subscriber,JsXRpmjI6rc,UCbmLUbSfJNH_14b32zyF_pQ,300.580000,25
8,931,2026-08-05T00:49:38+00:00,high_views_per_subscriber,kjtTvApeYbA,UCfD2bAwt3KMDIleIcOYPgsQ,303.220310,59
9,930,2026-08-05T00:49:22+00:00,high_views_per_subscriber,_3UaXtcDOwE,UC_69oRG20Y8TQ9YTAOgkMuA,305.485175,18
10,929,2026-08-05T00:49:05+00:00,high_views_per_subscriber,OedInwu1RUE,UCOAuLpescNtBactSMUGSe-Q,305.908219,33
11,928,2026-08-05T00:29:55+00:00,high_views_per_subscriber,Zc1tn4KSmfg,UCl2GCy-alo-HGy-vmTTQcOQ,307.908403,48
12,927,2026-08-05T00:29:40+00:00,high_views_per_subscriber,fTtFyg23rYA,UCxVdeFuO6yxnq9f0Eo0bmtA,310.064854,52
13,926,2026-08-05T00:29:24+00:00,high_views_per_subscriber,tJWTysZOroE,UCJdmdFGJxMRyNI2D2tyxtDQ,310.320242,13
14,925,2026-08-05T00:13:09+00:00,high_views_per_subscriber,zrJdLwEFep4,UCEZjDTulcHZGQW3DTdfazMw,315.127451,17
15,924,2026-08-05T00:12:53+00:00,high_views_per_subscriber,l1SF7Nm9Rg4,UCrybaylUJ7H2xUB14a1A7OQ,316.384058,7
16,923,2026-08-04T23:54:51+00:00,high_views_per_subscriber,jO1IhxjjloI,UChlTBWhQjL7Cem-n90MuXdA,312.190476,20
17,922,2026-08-04T23:34:11+00:00,high_views_per_subscriber,A_PkloZOdcs,UCVbN1m36bBuLx8dUMqPamrw,317.675113,56
18,921,2026-08-04T23:33:55+00:00,high_views_per_subscriber,ChhbWfuoBPs,UCKhtpgSSO6GL5SoUJDhrxOw,318.456897,47
19,920,2026-08-04T23:33:39+00:00,high_views_per_subscriber,wLtrxyXGKnk,UCW-tGrTiaZtlwG4Eo9LYDbQ,318.788991,40

====================================================================================================
TABLE: profile_queue
====================================================================================================

Schema:

    cid                             name     type  notnull dflt_value  pk
0     0                      channel_key     TEXT        0       None   1
1     1                       channel_id     TEXT        1       None   0
2     2                     channel_name     TEXT        0       None   0
3     3                  latest_video_at     TEXT        1       None   0
4     4                     last_seen_at     TEXT        1       None   0
5     5                  last_success_at     TEXT        0       None   0
6     6                         digested  INTEGER        1          0   0
7     7                  assigned_source     TEXT        1       None   0
8     8                     vidiq_failed  INTEGER        1          0   0
9     9               socialblade_failed  INTEGER        1          0   0
10   10                     needs_review  INTEGER        1          0   0
11   11                       claimed_by     TEXT        0       None   0
12   12                       claimed_at     TEXT        0       None   0
13   13               youtube_channel_id     TEXT        0       None   0
14   14            channel_id_claimed_by     TEXT        0       None   0
15   15            channel_id_claimed_at     TEXT        0       None   0
16   16  youtube_channel_id_attempted_at     TEXT        0       None   0
17   17               youtube_api_failed  INTEGER        1          0   0
18   18         youtube_api_attempted_at     TEXT        0       None   0
19   19           youtube_api_success_at     TEXT        0       None   0

Latest rows:

,channel_key,channel_id,channel_name,latest_video_at,last_seen_at,last_success_at,digested,assigned_source,vidiq_failed,socialblade_failed,needs_review,claimed_by,claimed_at,youtube_channel_id,channel_id_claimed_by,channel_id_claimed_at,youtube_channel_id_attempted_at,youtube_api_failed,youtube_api_attempted_at,youtube_api_success_at
0,@abcnews,@ABCNews,ABC News,2026-08-04T18:07:30+00:00,2026-08-05T02:07:45+00:00,2026-07-30T05:02:24+00:00,1,vidiq,1,1,0,None,None,UCBi2mrWuNuyYy4gbM6fU18Q,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T02:59:58+00:00
1,@allanwv,@allanwv,allanwv,2009-08-09T02:07:45+00:00,2026-08-05T02:07:45+00:00,2026-07-26T03:19:58+00:00,1,vidiq,0,0,0,youtube-api-487577,2026-07-30T16:31:43+00:00,UCcQQ3J0uzK4GO6BKF7KIYKA,None,None,None,1,2026-07-30T16:31:43+00:00,2026-07-26T03:19:58+00:00
2,@allrecipes,@allrecipes,Allrecipes,2026-07-28T17:51:27+00:00,2026-08-05T02:07:45+00:00,2026-07-30T17:29:54+00:00,1,vidiq,0,0,0,None,None,UC4tAgeVdaNB5vD_mBoxg50w,None,None,None,0,2026-07-30T16:31:43+00:00,2026-07-30T17:29:54+00:00
3,@ampexclusive,@AMPEXCLUSIVE,AMP,2026-08-03T16:55:36+00:00,2026-08-05T02:07:45+00:00,2026-07-27T03:55:24+00:00,1,vidiq,0,1,0,youtube-api-292221,2026-07-29T02:24:25+00:00,UCJbYdyufHR-cxOuY96KIoqA,None,None,None,1,2026-07-29T02:24:25+00:00,2026-07-27T03:55:24+00:00
4,@andreipiano,@AndreiPiano,Andrei Piano,2023-08-05T10:30:12+00:00,2026-08-05T02:07:45+00:00,2026-07-30T17:34:20+00:00,1,vidiq,0,0,0,None,None,UC6oPj0CXwGi1M280hUW-vyw,None,None,None,0,2026-07-30T16:31:43+00:00,2026-07-30T17:34:20+00:00
5,@asmontv,@AsmonTV,Asmongold TV,2026-08-04T15:56:48+00:00,2026-08-05T02:07:45+00:00,2026-07-27T03:51:11+00:00,1,socialblade,1,0,0,youtube-api-292221,2026-07-29T02:24:25+00:00,UCQeRaTukNYft1_6AZPACnog,None,None,2026-07-21T03:57:55+00:00,1,2026-07-29T02:24:25+00:00,2026-07-27T03:51:11+00:00
6,@ballislife,@ballislife,Ballislife,2026-08-03T21:55:00+00:00,2026-08-05T02:07:45+00:00,2026-07-27T03:53:25+00:00,1,vidiq,0,0,0,youtube-api-292221,2026-07-29T02:24:25+00:00,UC_zgOsTPdML6tol9hLYh4fQ,None,None,None,1,2026-07-29T02:24:25+00:00,2026-07-27T03:53:25+00:00
7,@baseballbatbros,@baseballbatbros,The Baseball Bat Bros,2026-07-28T16:51:39+00:00,2026-08-05T02:07:45+00:00,2026-07-30T17:20:24+00:00,1,socialblade,1,1,0,None,None,UCUC_sJGtV-oKdTw1s3oazwQ,None,None,None,0,2026-07-30T16:31:43+00:00,2026-07-30T17:20:24+00:00
8,@beardmeatsfood,@Beardmeatsfood,BeardMeatsFood,2026-08-03T17:55:41+00:00,2026-08-05T02:07:45+00:00,2026-07-27T04:31:56+00:00,1,vidiq,1,1,0,youtube-api-296385,2026-07-29T02:47:30+00:00,UCc9CjaAjsMMvaSghZB7-Kog,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-27T04:31:56+00:00
9,@bingecentral,@BingeCentral,Binge Central,2026-07-22T02:07:45+00:00,2026-08-05T02:07:45+00:00,2026-07-27T04:28:03+00:00,1,socialblade,1,0,0,youtube-api-296385,2026-07-29T02:47:30+00:00,UCSu7x-J8ESHojsq8mCvFOZw,None,None,2026-07-22T06:08:34+00:00,0,2026-07-29T02:47:30+00:00,2026-07-27T04:28:03+00:00
10,@blueyofficialchannel,@BlueyOfficialChannel,Bluey - Official Channel,2026-08-05T01:27:34+00:00,2026-08-05T02:07:45+00:00,2026-07-29T02:59:09+00:00,1,socialblade,1,1,0,None,None,UCVzLLZkDuFGAE2BGdBuBNBg,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T02:59:09+00:00
11,@bobdoessports,@Bobdoessports,Bob Does Sports,2026-07-31T21:02:42+00:00,2026-08-05T02:07:45+00:00,2026-07-30T17:20:37+00:00,1,vidiq,0,1,0,None,None,UCqr4sONkmFEOPc3rfoVLEvg,None,None,None,0,2026-07-30T16:31:43+00:00,2026-07-30T17:20:37+00:00
12,@bobross_thejoyofpainting,@bobross_thejoyofpainting,Bob Ross,2026-07-04T23:37:36+00:00,2026-08-05T02:07:45+00:00,2026-07-26T03:19:01+00:00,1,vidiq,0,1,0,youtube-api-487577,2026-07-30T16:31:43+00:00,UCxcnsr1R5Ge_fbTu5ajt8DQ,None,None,None,1,2026-07-30T16:31:43+00:00,2026-07-26T03:19:01+00:00
13,@briantylercohen,@briantylercohen,Brian Tyler Cohen,2026-08-05T01:11:45+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:00:26+00:00,1,socialblade,1,1,0,None,None,UCQANb2YPwAtK-IQJrLaaUFw,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:00:26+00:00
14,@calebhammer,@CalebHammer,Caleb Hammer,2026-08-04T02:07:45+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:01:12+00:00,1,vidiq,1,1,0,None,None,UCLe_q9axMaeTbjN0hy1Z9xA,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:01:12+00:00
15,@caylusblox,@caylusblox,CaylusBlox,2026-08-03T08:32:52+00:00,2026-08-05T02:07:45+00:00,2026-07-27T04:24:38+00:00,1,socialblade,1,1,0,youtube-api-296385,2026-07-29T02:47:30+00:00,UCsPMNatXCwqyUuJilBT73jg,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-27T04:24:38+00:00
16,@cboystv,@CboysTV,CboysTV,2026-08-01T02:27:04+00:00,2026-08-05T02:07:45+00:00,2026-07-27T03:54:37+00:00,1,vidiq,0,0,0,youtube-api-292221,2026-07-29T02:24:25+00:00,UCBNnILlexKYtJu-EGUvq_iA,None,None,None,1,2026-07-29T02:24:25+00:00,2026-07-27T03:54:37+00:00
17,@cleetusm,@CleetusM,Cleetus McFarland,2026-08-04T14:49:57+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:05:29+00:00,1,socialblade,1,0,0,None,None,UCh8f8vssLddD2PbnU3Ag_Bw,None,None,2026-07-22T01:45:16+00:00,0,2026-07-29T02:47:30+00:00,2026-07-29T03:05:29+00:00
18,@cnn,@CNN,CNN,2026-08-04T23:47:46+00:00,2026-08-05T02:07:45+00:00,2026-07-30T07:26:46+00:00,1,vidiq,1,1,0,None,None,UCupvZG-5ko_eiXAupbDfxWw,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:01:05+00:00
19,@cumtismgambles,@CumtismGambles,Cumtism Gambles,2026-08-02T16:55:36+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:01:14+00:00,1,vidiq,1,1,0,None,None,UCrgta1_fMLqmR0d4J5keyzg,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:01:14+00:00

====================================================================================================
TABLE: youtube_api_quota_usage
====================================================================================================

Schema:

   cid        name     type  notnull dflt_value  pk
0    0  quota_date     TEXT        0       None   1
1    1  units_used  INTEGER        1          0   0

Latest rows:

    quota_date  units_used
0   2026-08-04        9975
1   2026-08-03        2234
2   2026-08-02        8000
3   2026-08-01        8000
4   2026-07-31        8000
5   2026-07-30        8000
6   2026-07-29        8000
7   2026-07-28        3934
8   2026-07-27         274
9   2026-07-26        8000
10  2026-07-25        8000
11  2026-07-24        8000
12  2026-07-23        8000
13  2026-07-22        8000

In [7]:
display(preview_table('profile_queue'))

,channel_key,channel_id,channel_name,latest_video_at,last_seen_at,last_success_at,digested,assigned_source,vidiq_failed,socialblade_failed,needs_review,claimed_by,claimed_at,youtube_channel_id,channel_id_claimed_by,channel_id_claimed_at,youtube_channel_id_attempted_at,youtube_api_failed,youtube_api_attempted_at,youtube_api_success_at
0,@abcnews,@ABCNews,ABC News,2026-08-04T18:07:30+00:00,2026-08-05T02:07:45+00:00,2026-07-30T05:02:24+00:00,1,vidiq,1,1,0,None,None,UCBi2mrWuNuyYy4gbM6fU18Q,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T02:59:58+00:00
1,@allanwv,@allanwv,allanwv,2009-08-09T02:07:45+00:00,2026-08-05T02:07:45+00:00,2026-07-26T03:19:58+00:00,1,vidiq,0,0,0,youtube-api-487577,2026-07-30T16:31:43+00:00,UCcQQ3J0uzK4GO6BKF7KIYKA,None,None,None,1,2026-07-30T16:31:43+00:00,2026-07-26T03:19:58+00:00
2,@allrecipes,@allrecipes,Allrecipes,2026-07-28T17:51:27+00:00,2026-08-05T02:07:45+00:00,2026-07-30T17:29:54+00:00,1,vidiq,0,0,0,None,None,UC4tAgeVdaNB5vD_mBoxg50w,None,None,None,0,2026-07-30T16:31:43+00:00,2026-07-30T17:29:54+00:00
3,@ampexclusive,@AMPEXCLUSIVE,AMP,2026-08-03T16:55:36+00:00,2026-08-05T02:07:45+00:00,2026-07-27T03:55:24+00:00,1,vidiq,0,1,0,youtube-api-292221,2026-07-29T02:24:25+00:00,UCJbYdyufHR-cxOuY96KIoqA,None,None,None,1,2026-07-29T02:24:25+00:00,2026-07-27T03:55:24+00:00
4,@andreipiano,@AndreiPiano,Andrei Piano,2023-08-05T10:30:12+00:00,2026-08-05T02:07:45+00:00,2026-07-30T17:34:20+00:00,1,vidiq,0,0,0,None,None,UC6oPj0CXwGi1M280hUW-vyw,None,None,None,0,2026-07-30T16:31:43+00:00,2026-07-30T17:34:20+00:00
5,@asmontv,@AsmonTV,Asmongold TV,2026-08-04T15:56:48+00:00,2026-08-05T02:07:45+00:00,2026-07-27T03:51:11+00:00,1,socialblade,1,0,0,youtube-api-292221,2026-07-29T02:24:25+00:00,UCQeRaTukNYft1_6AZPACnog,None,None,2026-07-21T03:57:55+00:00,1,2026-07-29T02:24:25+00:00,2026-07-27T03:51:11+00:00
6,@ballislife,@ballislife,Ballislife,2026-08-03T21:55:00+00:00,2026-08-05T02:07:45+00:00,2026-07-27T03:53:25+00:00,1,vidiq,0,0,0,youtube-api-292221,2026-07-29T02:24:25+00:00,UC_zgOsTPdML6tol9hLYh4fQ,None,None,None,1,2026-07-29T02:24:25+00:00,2026-07-27T03:53:25+00:00
7,@baseballbatbros,@baseballbatbros,The Baseball Bat Bros,2026-07-28T16:51:39+00:00,2026-08-05T02:07:45+00:00,2026-07-30T17:20:24+00:00,1,socialblade,1,1,0,None,None,UCUC_sJGtV-oKdTw1s3oazwQ,None,None,None,0,2026-07-30T16:31:43+00:00,2026-07-30T17:20:24+00:00
8,@beardmeatsfood,@Beardmeatsfood,BeardMeatsFood,2026-08-03T17:55:41+00:00,2026-08-05T02:07:45+00:00,2026-07-27T04:31:56+00:00,1,vidiq,1,1,0,youtube-api-296385,2026-07-29T02:47:30+00:00,UCc9CjaAjsMMvaSghZB7-Kog,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-27T04:31:56+00:00
9,@bingecentral,@BingeCentral,Binge Central,2026-07-22T02:07:45+00:00,2026-08-05T02:07:45+00:00,2026-07-27T04:28:03+00:00,1,socialblade,1,0,0,youtube-api-296385,2026-07-29T02:47:30+00:00,UCSu7x-J8ESHojsq8mCvFOZw,None,None,2026-07-22T06:08:34+00:00,0,2026-07-29T02:47:30+00:00,2026-07-27T04:28:03+00:00
10,@blueyofficialchannel,@BlueyOfficialChannel,Bluey - Official Channel,2026-08-05T01:27:34+00:00,2026-08-05T02:07:45+00:00,2026-07-29T02:59:09+00:00,1,socialblade,1,1,0,None,None,UCVzLLZkDuFGAE2BGdBuBNBg,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T02:59:09+00:00
11,@bobdoessports,@Bobdoessports,Bob Does Sports,2026-07-31T21:02:42+00:00,2026-08-05T02:07:45+00:00,2026-07-30T17:20:37+00:00,1,vidiq,0,1,0,None,None,UCqr4sONkmFEOPc3rfoVLEvg,None,None,None,0,2026-07-30T16:31:43+00:00,2026-07-30T17:20:37+00:00
12,@bobross_thejoyofpainting,@bobross_thejoyofpainting,Bob Ross,2026-07-04T23:37:36+00:00,2026-08-05T02:07:45+00:00,2026-07-26T03:19:01+00:00,1,vidiq,0,1,0,youtube-api-487577,2026-07-30T16:31:43+00:00,UCxcnsr1R5Ge_fbTu5ajt8DQ,None,None,None,1,2026-07-30T16:31:43+00:00,2026-07-26T03:19:01+00:00
13,@briantylercohen,@briantylercohen,Brian Tyler Cohen,2026-08-05T01:11:45+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:00:26+00:00,1,socialblade,1,1,0,None,None,UCQANb2YPwAtK-IQJrLaaUFw,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:00:26+00:00
14,@calebhammer,@CalebHammer,Caleb Hammer,2026-08-04T02:07:45+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:01:12+00:00,1,vidiq,1,1,0,None,None,UCLe_q9axMaeTbjN0hy1Z9xA,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:01:12+00:00
15,@caylusblox,@caylusblox,CaylusBlox,2026-08-03T08:32:52+00:00,2026-08-05T02:07:45+00:00,2026-07-27T04:24:38+00:00,1,socialblade,1,1,0,youtube-api-296385,2026-07-29T02:47:30+00:00,UCsPMNatXCwqyUuJilBT73jg,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-27T04:24:38+00:00
16,@cboystv,@CboysTV,CboysTV,2026-08-01T02:27:04+00:00,2026-08-05T02:07:45+00:00,2026-07-27T03:54:37+00:00,1,vidiq,0,0,0,youtube-api-292221,2026-07-29T02:24:25+00:00,UCBNnILlexKYtJu-EGUvq_iA,None,None,None,1,2026-07-29T02:24:25+00:00,2026-07-27T03:54:37+00:00
17,@cleetusm,@CleetusM,Cleetus McFarland,2026-08-04T14:49:57+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:05:29+00:00,1,socialblade,1,0,0,None,None,UCh8f8vssLddD2PbnU3Ag_Bw,None,None,2026-07-22T01:45:16+00:00,0,2026-07-29T02:47:30+00:00,2026-07-29T03:05:29+00:00
18,@cnn,@CNN,CNN,2026-08-04T23:47:46+00:00,2026-08-05T02:07:45+00:00,2026-07-30T07:26:46+00:00,1,vidiq,1,1,0,None,None,UCupvZG-5ko_eiXAupbDfxWw,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:01:05+00:00
19,@cumtismgambles,@CumtismGambles,Cumtism Gambles,2026-08-02T16:55:36+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:01:14+00:00,1,vidiq,1,1,0,None,None,UCrgta1_fMLqmR0d4J5keyzg,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:01:14+00:00
20,@danny,@danny,Danny Duncan,2026-07-29T22:42:35+00:00,2026-08-05T02:07:45+00:00,2026-07-27T03:55:26+00:00,1,vidiq,0,0,0,youtube-api-292221,2026-07-29T02:24:25+00:00,UC94lW_-Hr_uA7RcJ3D-WPOg,None,None,None,1,2026-07-29T02:24:25+00:00,2026-07-27T03:55:26+00:00
21,@daydrian,@daydrian,D’Aydrian Harding,2026-07-31T00:58:56+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:00:30+00:00,1,vidiq,1,1,0,None,None,UCSiqOJepPF7KYrPRWFmXqOQ,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:00:30+00:00
22,@dfbguide,@DFBGuide,DFBGuide,2026-07-31T10:49:48+00:00,2026-08-05T02:07:45+00:00,2026-07-27T04:19:14+00:00,1,socialblade,1,0,0,youtube-api-296385,2026-07-29T02:47:30+00:00,UCnpWedLQdHpZqhgTLdB9Yyg,None,None,2026-07-21T22:13:19+00:00,0,2026-07-29T02:47:30+00:00,2026-07-27T04:19:14+00:00
23,@disneyjr,@disneyjr,Disney Jr.,2025-08-04T02:34:06+00:00,2026-08-05T02:07:45+00:00,2026-07-30T17:32:06+00:00,1,vidiq,0,1,0,None,None,UCNcdbMyA59zE-Vk668bKWOg,None,None,None,0,2026-07-30T16:31:43+00:00,2026-07-30T17:32:06+00:00
24,@donut,@Donut,Donut,2026-07-29T12:11:54+00:00,2026-08-05T02:07:45+00:00,2026-07-29T03:00:19+00:00,1,vidiq,1,1,0,None,None,UCL6JmiMXKoXS6bpP1D3bk8g,None,None,None,0,2026-07-29T02:47:30+00:00,2026-07-29T03:00:19+00:00

In [8]:
# Close last: every cell above queries through this connection.
connection.close()